### ISSUE TITLE
[checkstyle-tester] ArrayOutOfBoundsException in  launch.groovy when commit id is not set

### ISSUE THREAD

**Issue by MEZk** [checkstyle/contribution#144]
There are lines in projects-for-circle.properties where commit tag or SHA-1 is not set. It leads to ArrayOutOfBoundsException in launch.groovy.

```
Testing Checkstyle started
Caught: java.lang.ArrayIndexOutOfBoundsException: 3
java.lang.ArrayIndexOutOfBoundsException: 3
	at launch$_generateCheckstyleReport_closure1.doCall(launch.groovy:69)
	at launch.generateCheckstyleReport(launch.groovy:62)
	at launch$generateCheckstyleReport$0.callCurrent(Unknown Source)
	at launch.run(launch.groovy:10)
```

@romani 
How should the script know whether the 4th element (starting from 0) in the line is commit id or there is an exclude section? I propose to have all elements in line specified: REPO_NAME|REPO_TYPE|REPO_URL|COMMIT_ID|EXCLUDES or we can follow the rule: if line contains 4 elements than the 4th element is commit id. If line contains 5 elements than 4th is commit id and 5th is excludes.

**Comment by romani** [comment]
Config line should be pipe delimited, if element is absent there should be `||`
