### ISSUE TITLE
Turn tester failsOnError into a property

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#152]
https://github.com/checkstyle/contribution/blob/3ffb678b666e3e26c4227ca41d5a35237be343cd/checkstyle-tester/pom.xml#L59
This line needs to be turned into a property as a default value of `false` damages no exception testing.

In no exception testing, we want an exception to result in a build failure.
In a regression testing, we don't want an exception to result in a build failure, but be listed as a type of violation in the reports for differences.

`groovy` and `launch_diff` need to be changed to specify and set the property to `false`.
Default property in POM should be `true`.

**Comment by romani** [comment]
https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html#failsOnError

doe not have user property, so we should move it to local property of our pom file.

**Comment by rnveach** [comment]
Since groovy's diff is 2 separate programs, to enable this feature in it, we would have to have one send the other an optional argument.
Maybe we could use [CliBuilder](http://docs.groovy-lang.org/2.4.7/html/gapi/groovy/util/CliBuilder.html)

**Comment by romani** [comment]
fix is merged

**Comment by rnveach** [comment]
@romani Fix wasn't applied to groovy program.

**Comment by MEZk** [comment]
@romani 
Assign. I will provide a fix.

**Comment by romani** [comment]
@MEZk, discuss this with rnveach.

**Comment by rnveach** [comment]
@MEZk go right ahead if you want to.

**Comment by rnveach** [comment]
the 2 fixes close the issue
