### ISSUE TITLE
Some excludes in tester are too broad

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#154]
Some excludes are too broad in tester, and most likely caused issues in regression (https://github.com/checkstyle/checkstyle/pull/3737#pullrequestreview-17790852) where good files for processing were incorrectly being ignored.

Example:
https://github.com/checkstyle/contribution/blob/079b9dec976473d3d8f9297830e0d0c850f3054d/checkstyle-tester/projects-to-test-on.properties#L47
> `**/**/test/**/*`

Some regression scripts put all projects into one directory, so this line is going to affect all of them incorrectly. Excludes should only affect their own project, no matter where it is stored or stored with.

We should review all excludes and verify they aren't too broad.
IMO, each one should mention the project name somehow.

**Comment by romani** [comment]
fix is meged
