### ISSUE TITLE
Ignore excludes in diff reports only

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#155]
Based on Issue #154, I question why we need excludes in diff reports.
I am not talking about no-exception testing. I am **ONLY** talking about any script that uses `patch-diff-report-tool`.

We already turn exceptions into violations and treat them the same in reports. If they stay the same we ignore them, if they change we report them as a difference.
Referenced issue had a problem with excludes and should be fixed, but why do we care about excludes? Main reason for excludes is to skip files that aren't parsable as they produce exceptions. But like I said above, exceptions aren't an issue in these regressions. We also want to know any difference in these exceptions, like if we fix grammar parsing. Excludes would have to change for that if it does happen.

So are we losing anything by ignoring excludes in diff reports? I don't think so. Only negative side-effect may be more files to parse, which may not be a bad thing.

I propose we change `launch_diff` and `diff.groovy` to ignore the exclude column in the properties file. **We should not change any properties files at all.** We will just not read their values making it **like** they don't exist.
Since `diff.groovy`/`launch.groovy` are 2 separate programs, `diff` will need to send a new parameter to `launch` to turn off reading the excludes. Default behavior of `launch.groovy` should still read exclude column as it is needed for no-exception testing.

**Comment by MEZk** [comment]
@rnveach 
1) Sometimes we add new project to test on. These projects may contain non-compilable sources as Checkstyle has. We need to exclude them.
2) We use Guava to test checks that cover Googly Style config. Reports that we analyze are generated this way https://github.com/checkstyle/checkstyle/wiki/How-to-generate-Checkstyle-report-for-Google-Guava-project . ```**/**/test/**/*,**/guava-gwt/src-super/**/*,**/guava-tests/**/*,**/guava-gwt/test-super/**/*``` are excluded in the reports.

We need to discuss the points mentioned.

**Comment by rnveach** [comment]
> projects may contain non-compilable sources as Checkstyle has. We need to exclude them.

Why do we **need** to? Non-compilables will usually result in an exception if we try to parse them. We added `haltOnException` and `failsOnError` to our config/pom, so these exceptions will just be added to our reports for differences. With these 2 on, Checkstyle will just keep working through the project even if it hits many exceptions.

> https://github.com/checkstyle/checkstyle/wiki/How-to-generate-Checkstyle-report-for-Google-Guava-project

This doesn't use our `patch-diff-report-tool` so I am not talking about changing it.
This is for only our programs that eventually run `patch-diff-report-tool` like `launch_diff` and `diff.groovy`.

**Comment by MEZk** [comment]
@rnveach 
It will require to add new option```ignoreExcludes``` (optional, default is false) for launch.groovy. diff.groovy should set this option to true.

Lets postpone the fix till https://github.com/checkstyle/contribution/pull/170 to avoid merge conflicts.

**Comment by MEZk** [comment]
@rnveach 
What is your opinion?

**Comment by rnveach** [comment]
> What is your opinion?

On if we need the new option `ignoreExcludes`? Yes, we will as there is no other way to talk to launch from diff.

**Comment by MEZk** [comment]
@rnveach 
I mean the option should be implemented only for launch.groovy. There is no need in making it as an option for diff.groovy.

**Comment by rnveach** [comment]
That sounds fine to me.

**Comment by MEZk** [comment]
@rnveach 
I am stuck with the short name for ```ignoreExcludes```) We already have ```-i``` as a short name for ```ignoreExceptions```. 

My examples
1) iexcl - too long
2) noExcludes -> ne - looks confusing
3) ie - may be confusing (ignoreExceptions -> ie)

Any ideas?

**Comment by rnveach** [comment]
@MEZk Are we required to have a short name?
If user isn't going to use this option normally, then I say lets not give it a short name.

**Comment by romani** [comment]
I agree with rnveach.
give it any letter like "g" (next after "i" in "ignoreExcludes") or you can name option as "noExcludes" and short name as "n".

**Comment by romani** [comment]
fix is merged.
