### ISSUE TITLE
releasenotes-builder: problem with twitter at 'Breaking backward compatibility'

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#163]
https://api.travis-ci.org/jobs/196233795/log.txt?deansi=true

```
Checkstyle 7.5 - http://checkstyle.sourceforge.net/releasenotes.html#Release_7.5
breakingMessages
New functionality: 2
Bug fixes: 8
```

What is "breakingMessages" ?
expected smth like "Breaking backward compatibility: 1"

**Comment by MEZk** [comment]
@romani 
You can close the issue as it was fixed at #171
