### ISSUE TITLE
Create travis test launches for groovy tester

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#166]
Like title suggests. We request users use this program for work in checkstyle. We should create some type of test(s) to verify it is functioning correctly during updates to its functionality.

**Comment by rnveach** [comment]
Groovy supports junit and cobertura for code coverage
http://docs.groovy-lang.org/docs/latest/html/documentation/core-testing-guide.html#_junit_3
http://groovy-lang.org/testing.html#_test_code_coverage

**Comment by MEZk** [comment]
@rnveach
1) Let's add an execution of diff.groovy into travis.yml. For example, it can generate diff reports against Guava on master as a base branch and master as a patch branch just to verify that the script is not failing on start. 
2) Implement UTs.

**Comment by romani** [comment]
I would postpone UT creation for future. Simple launch of script will test most of functionality

**Comment by rnveach** [comment]
Fix was merged, and we won't be creating UTs for these groovy scripts
So I am closing the issue
