### ISSUE TITLE
diff.groovy tool should have options to specify base config and patch config

### ISSUE THREAD

**Issue by MEZk** [checkstyle/contribution#167]
Sometimes we need to generate diff reports using different checkstyle configurations:
1) base config
2) patch config

For example, we change the option name and regexp for ParameterNameCheck. Now I have to change diff.groovy script and manually hardcode two configs in my local branch.

It would be good If diff.groovy had these two options (baseCheckstyleCfg, patchCheckstyleCfg). If patchCheckstyleCfg is not set, then diff.groovy will use baseCheckstyleCfg to generate Checkstyle report for both base and patch branches. In other words, baseCheckstyleCfg should be treated as required option, patchCheckstyleCfg should be optional.

Thus, what should be done:
1) New options should be added.
2) Documentation should be updated.

@romani @rnveach 
Please, share your opinions.

**Comment by romani** [comment]
Good

**Comment by rnveach** [comment]
Just 2 questions.
Do we need `Checkstyle` in the name? Isn't (base|patch)Config enough? We only have one type of config for this utility. The other one is a list file.
Would it be better to have 3 options? config, baseConfig, patchConfig. If config is set, setting other 2 should give an error. If base or patch is set, it requires both and no config set otherwise it is an error. Obviously setting config would be both base and patch config to use.

Otherwise I am fine with the idea.

**Comment by MEZk** [comment]
Too many options is not a good idea as for me. 
I'm OK with the proposal that we do not need checkstyle prefix in names.

**Comment by romani** [comment]
we put "checkstyle" in name only to make it clear that config is not for tool , but for checkstyle that is running under tool.
config of tool that we run is list of projects (property file).
checkstyle config is xml file.

Are you sure you want to change this ? keep in mind that this tool will be used by contributors who do not want to spend much time to read our documentation details.

**Comment by rnveach** [comment]
> config of tool that we run is list of projects (property file).

Option name doesn't have `config` in it. Do we call it config in any of our documentation?

If we are hesitant to change it, then lets leave it as it is.

**Comment by romani** [comment]
> localGitRepo (r) - path to the local Checkstyle repository;
baseBranch (b) - name of the base branch in local Checkstyle repository (default is master branch);
patchBranch (p) - name of the branch with your changes;
checkstyleCfg (c) - path to the file with Checkstyle configuration;
listOfProjects (l) - path to the file which contains the projects which sources will be analyzed by Checkstyle during report generation.

as we start to name property file as "list" , `checkstyleCfg` looks strange as all other options mean/have cheackstyle in descriptions but not in names.

I am ok to change option to `(base|patch)Config`.

> Would it be better to have 3 options? config, baseConfig, patchConfig

lets have 3 options - "(base|patch)Config" + "config".  We will need extra validation for arguments but CLI command will be read clearly.

**Comment by MEZk** [comment]
Do we need yo use the same naming convention for launch.groovy? I think, yes.

**Comment by romani** [comment]
Yes. Let's try.

**Comment by rnveach** [comment]
Fixed is merge
