### ISSUE TITLE
update windows CI to have run of groovy test tools

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#177]
base on #79 .

We need to have example of how to run groovy tool on windows, an test that it works on windows.

File 
https://github.com/checkstyle/contribution/blob/master/appveyor.yml
contains only example for launch.sh, we need the same launches for 	launch.groovy and diff.groovy

**Comment by rnveach** [comment]
Windows test should use the new option in https://github.com/checkstyle/contribution/issues/82 `--shortFilePaths` as Windows has issues with deeply nested folders as seen in issue.

**Comment by MEZk** [comment]
@rnveach @romani 
Only diff.groovy need to have the new option implemented as diff.groovy uses path-diff-report-tool to generate diff reports.

**Comment by MEZk** [comment]
@rnveach 
> Windows test should use the new option in #82 --shortFilePaths as Windows has issues with deeply nested folders as seen in issue and will let other Windows users know that they should use it by default.

Will be addressed at https://github.com/checkstyle/contribution/issues/191
In scope of #177 I will just create Windows test launcher.

**Comment by romani** [comment]
Fix is merged

**Comment by romani** [comment]
fix is merged.
