### ISSUE TITLE
diff.groovy should skip tests on patch-diff-report-tool

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#181]
With the soon-to-be introduction of more tests for patch-diff-report-tool in #176 , diff.groovy's use of patch-diff-report-tool will run the tests unnecessarily each time diff.groovy is run.

The packaging of patch-diff-report-tool should skip any and all tests by default in diff.groovy.

**Comment by romani** [comment]
even before #176 - it is not required to run tests, it is just missed argument "-DskipTests" , could be fixed at any time.

Uts of patch-diff-report-tool  are checked by  https://github.com/checkstyle/contribution/blob/master/.travis.yml#L17

**Comment by romani** [comment]
fix is merged
