### ISSUE TITLE
FileAlreadyExistsException in launch.groovy

### ISSUE THREAD

**Issue by MEZk** [checkstyle/contribution#193]
If all lines in the list of projects file, which is received by launch.groovy, are commented out, the execution process will never step inside [the loop](https://github.com/MEZk/contribution/blob/8ecf0589ff1b2441fd80113f38fbbbda7d7b5db4/checkstyle-tester/launch.groovy#L64-L64) and [Files.createFile(Paths.get("$srcDir/empty_file"))](https://github.com/MEZk/contribution/blob/8ecf0589ff1b2441fd80113f38fbbbda7d7b5db4/checkstyle-tester/launch.groovy#L93-L93) will throw FileAlreadyExistsException.

**Comment by romani** [comment]
Fix is merged
