### ISSUE TITLE
restore launch.sh testing in appveyor

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#203]
from #201 

configuration was removed to unblock PR acceptance process.
We do not use launch.sh now actively, as there is groovy variant of it.

**Comment by rnveach** [comment]
I upgraded cygwin to the latest (2.879) and launch.sh has no issue running as is.
Could failure before have been a bug in cygwin (2.877)?

**Comment by romani** [comment]
> Could failure before have been a bug in cygwin (2.877)?

most likely ... can we upgrade to new version at appveyor ? might be possible to file issue against appveyor to upgrade.

**Comment by rnveach** [comment]
I recommend closing this as we are not going back to SH scripts and use groovy.
