### ISSUE TITLE
releasenotes-builder: missed new feature

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#206]
issue https://github.com/checkstyle/checkstyle/issues/3437
one more : https://github.com/checkstyle/checkstyle/issues/3892

has label "new feature" but it is not present in releasenotes after 7.6, that forced me to create 7.6.1 release instead of 7.7 .

Release notes skip information for update for all our plugins. That might result in wave of problems.

TODO: investigate a reason of missed "new feature" group in release notes of 7.6.1 - checkstyle.sourceforge.net/releasenotes.html#Release_7.6.1

link to all closed "new feature" issues - https://github.com/checkstyle/checkstyle/issues?q=is%3Aissue+label%3A%22new+feature%22+is%3Aclosed+sort%3Aupdated-desc

**Comment by romani** [comment]
one more problem - https://github.com/checkstyle/checkstyle/issues/3329 does not have label  and build is not failed

**Comment by romani** [comment]
problem is even bigger:

```
$git log --pretty=format:"%s" checkstyle-7.6...checkstyle-7.6.1 | grep -vE "^config:|minor:|infra:|spelling:|maven-release|^doc:" > 1.log

2.log is created by copy-paste of web content

$ cut -d " " -f2 1.log | cut -c2-5 | sort | uniq > 1_numbers.log

$ cut -d "#" -f2 2.log | grep -E "^[0-9]" | sort | uniq > 2_numbers.log

$ diff -u 1_numbers.log 2_numbers.log 
--- 1_numbers.log   2017-03-28 11:49:10.040920921 -0700
+++ 2_numbers.log   2017-03-28 11:49:14.329127713 -0700
@@ -2,10 +2,7 @@
 3172
 3329
 3437
-3491
 3612
-3648
-3685
 3700
 3731
 3755
@@ -14,38 +11,20 @@
 3843
 3848
 3850
+3868
 3869
 3883
 3888
 3892
 3896
-3897
-3900
 3904
 3906
 3908
-3910
-3929
-3943
-3954
-3958
-3961
 3962
-3965
-3970
-3976
-3985
-3986
 3989
-3991
-3999
-4003
-4014
 4030
-4042
 4044
 4045
 4055
 4081
 4093
-4095

$ diff -u 1_numbers.log 2_numbers.log | grep -E "^(\+|-)[0-9]"
-3491
-3648
-3685
+3868
-3897
-3900
-3910
-3929
-3943
-3954
-3958
-3961
-3965
-3970
-3976
-3985
-3986
-3991
-3999
-4003
-4014
-4042
-4095
```

**Comment by MEZk** [comment]
@romani 
> Release notes skip information for update for all our plugins. That might result in wave of problems.

It was done intentionally.
https://github.com/MEZk/contribution/blob/7ca5d6650f251bb096c97a780908c899d3b69fd6/releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java#L59-L59

**Comment by romani** [comment]
yes I know,  it is not a problem - it is expected behavior, looks like @rnveach made this comment.

But here was update for jgit , that might be a reason of problem:
```
$ git log --pretty=format:"%s" checkstyle-7.6...checkstyle-7.6.1 | grep -E "^config:"
config: update to 7.6.1-SNAPSHOT
config: bump slf4j-simple version to 1.7.24
config: bump version of org.eclipse.jgit to 4.6.1.201703071140-r
config: bump version to commons-cli 1.4
config: bump org.jacoco.agent version to 0.7.9
config: bump equalsverifier version to 2.2.1
config: bump ant version to 1.10.1
config: bump wagon-ssh version ro 2.12
config: bump nexus-staging-maven-plugin version to 1.6.8
config: bump slf4j-simple version to 1.7.23
config: bump maven-shade-plugin version to 3.0.0
config: bump forbiddenapis version to 2.3
config: bump build-helper-maven-plugin version to 3.0.0
config: bump checkstyle version
```

**Comment by rnveach** [comment]
> one more problem - checkstyle/checkstyle#3329 does not have label and build is not failed

`NotesBuilder.getIssueLabelFrom` is returning `easy`.

> .filter(input -> Arrays.binarySearch(Constants.ISSUE_LABELS, input.getName()) != -1)

This looks like an issue. Binary search returns `>= 0` if it exists in array and `< 0` on where it should be inserted into array if it doesn't exist.
Condition should be checking `>= 0`.

With this change, I get the following error when running:
`[ERROR] Issue #3329 does not have breaking compatibility, bug, miscellaneous, new feature label!`

**Comment by romani** [comment]
Fix is merged
