### ISSUE TITLE
launch.groovy: documentation is not clear compared to diff.groovy and missing some things

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#211]
[`launch.groovy`](https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#launchgroovy-checkstyle-report-generation) ~~documentation doesn't specify that the checkstyle version being run against, the PR branch, has to be done manually (`mvn install`).~~ Edit: I see it now, but it should reference to grab version from Checkstyle's pom.

It is also not clear that it's output goes ~~to specific location~~ under specific file name. Since reports like diff's aren't generated, we need to be able to guide user to how to give us those results manually.
Edit: I think we are just missing the main report file name. I don't remember if it is still `index.html`.

I am also not sure if we need to specify POM checkstyle version to make sure the right version is used.
Edit: Links are there, but they don't point to the right places. Maybe we should add more on how to verify versions.

**Comment by romani** [comment]
Fix is merged
