### ISSUE TITLE
Switch to Fremarker for release notes generation

### ISSUE THREAD

**Issue by MEZk** [checkstyle/contribution#212]
> Thymeleaf better suites for HTML generation. And we generate xml that looks like html on first sight , but we do care about its structure (no extra spaces and .....) so it over complicate Thymeleaf template and Freemarker looks much better and give us full control of content generation.

From my point of view, Fremarker has better conditions handling.
We need to check whether the fremarker can deal with the problem described in https://github.com/checkstyle/contribution/pull/205. If Fremarker does not have the problem it is OK to use it.

**Comment by romani** [comment]
fix is merged.
