### ISSUE TITLE
checkstyle-tester: support regression on new checks/tokens

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#213]
This has come up twice in PRs where regression is requested. The latest is at https://github.com/checkstyle/checkstyle/pull/4149#issuecomment-293634837 .

When a new token is introduced into an existing check, there is no way to run `diff.groovy`.
Groovy requires a before image (master) and an after image (PR branch). When specifying a brand new token alone, there is nothing to run it against in the before image as the token doesn't exist. Attempting to run a configuration with a token that doesn't exist will get something similar to the following error:
> Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "METHOD_REF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.SeparatorWrapCheck

Users are forced to run `launch.groovy` which doesn't automatically generate a main index page, which allows us to instantly see which projects have differences/violations.

We should add support for these types of scenarios in `diff.groovy` and `patch-diff-report-tool`.
For this option to be activated, the user should only need to specify the patch branch and the patch config.
We should use a special option in `diff.groovy` to specify this type of run like `--patchOnly`.

It should act like the before image run produced no violations.
This type of option will reduce the regression run by half as it is only doing the PR run and not the master run.

**Comment by MEZk** [comment]
@rnveach 
diff.groovy supports xml configuration for the branch before changes (master) and PR branch: baseConfig and patchConfig. So, what is the problem with it? You need to pass to configs to diff.groovy: one without a new token and one with.

**Comment by rnveach** [comment]
> there is no way to run launch.groovy.

I'm sorry, I meant `diff.groovy`.
I will change the post.

> You need to pass to configs to diff.groovy: one without a new token and one with.

What do you suggest for before image when token is brand new and is not supported in master and we just want violations on just that token?
The only way I see is to apply all acceptable tokens to the check in both and hope that regression of the tokens don't intersect one another. [We have one check, `ParenPad`, which had this happen](https://github.com/checkstyle/checkstyle/issues/4175). One token was being picked up in master when another was set, and regression always showed 0 differences until we ran regression on single tokens.
So adding all tokens will just give us the regression of all those tokens, not regression on the individual isolated tokens.

> What do you mean? I do not understand the idea. Please, explain.

[We have to call `generateCheckstyleReport` twice, once for master and once for patch](https://github.com/checkstyle/contribution/blob/35d35dfcc48e2022403231e41aac8bf96126acc9/checkstyle-tester/diff.groovy#L50-L51). Each call runs on all projects defined in config, so full regression usually takes some time.
If token is brand new, master can never have any violations on it if the token is isolated and we want to see just the results of that token. By dropping running CS on master, we only have to run it on the patch, hence dividing regression time in half.
This would allow us to see diff reports for everything, and not have to use `launch.groovy` at all anymore.

**Comment by MEZk** [comment]
@rnveach 
> This would allow us to see diff reports for everything, and not have to use launch.groovy at all anymore.

Do you mean that we need to support only one script (diff.groovy) which will include all logic from launch. groovy and generate both diff reports and simple Checkstyle reports if ```--patchOnly``` is specified?

**Comment by rnveach** [comment]
@MEZk 

> > This would allow us to see diff reports for everything, and not have to use launch.groovy at all anymore.

> Do you mean that we need to support only one script (diff.groovy)

We still have to support both since `diff.groovy` calls `launch.groovy`. I wasn't referring to combining the 2 into 1. My statement meant that users wouldn't need to know how to work `launch.groovy`. They should only be using `diff.groovy`. It's reporting is a lot nice, imo, than `launch.groovy`'s and we keep adding more to diff's. `launch`'s report is out of our control for additions/modifications.

> generate both diff report and simple Checkstyle report if --patchOnly is specified?

I expect only `diff`'s report for reasons I stated in previous paragraph.

**Comment by MEZk** [comment]
@rnveach 
Ok,  I understood. I'll try to implement your idea.

**Comment by romani** [comment]
@rnveach and @MEZk can smb explain me reason of fix in`diff.groovy` ?

According to initial problem, we lack summary page for `launch.groovy` that is very convenient, I agree.
If that is what we need - we need to change `launch.groovy`. It will very logical even for new contributors.

**Comment by rnveach** [comment]
> It will very logical even for new contributors.

It is actually not clear to new contributors when to use `diff.groovy` and when to use `launch.groovy`. Most of the time we tell them to run diff reports because they are just fixing logic. They don't see it as clear that they must run launch for single side regression for new tokens/checks. In mentioned issue, user was modifying master so he could still use `diff.groovy` in regression for a new token.

Most of this may just mean we need more documentation, but I want to go down the other path because...

> we lack summary page for launch.groovy 

With summary page of launch's report, it will require us to have different code for summary generation as their main report's layouts are different. It may also require a new option in launch as diff calls it and doesn't need it's summary. We may also not be able to provide the same counts because of launch's restricted layout.

I am also pushing that we drop launch's report **completely** (this report: http://rveach.no-ip.org/checkstyle/regression/reports/20/checkstyle/index.html). I think our report looks better (this report: http://rveach.no-ip.org/checkstyle/regression/reports/16/checkstyle/index.html), and it allows us to link to direct violations in the report which launch's doesn't. We should be looking at the same report styling for all our reviewing needs. It provides consistency for everyone. This also allows us to drop using launch completely as everyone will now run reports through `diff.groovy` regardless of the type of change. So users only need to learn to use this one utility. launch's report is also not under our control, while `patch-diff-report-tool`'s report is, which allows us to change and add anything we need.

**Comment by MEZk** [comment]
@romani 

I started fixing diff.groovy in order to implement summary page generation for the case when base branch was not specified, but we decided that change of path-diff-report-tool would be better idea.

@rnveach 

> With summary page of launch's report, it will require us to have different code for summary generation as their main report's layouts are different. It may also require a new option in launch as diff calls it and doesn't need it's summary. We may also not be able to provide the same counts because of launch's restricted layout.

Agree.

@rnveach 
>  This also allows us to drop using launch completely as everyone will now run reports through diff.groovy

I thought that we decided not to mix two utilities. ```launch.groovy``` should stay behind the scene. It should be invoked by ```diff.groovy``` transparent to the user. User need not know that ```diff.groovy``` runs ```launch.groovy``` inside.

@romani 

> So users only need to learn to use this one utility.

And this will be a perfect solution as newbie contributors will not need to learn all our utilities.

**Comment by rnveach** [comment]
> launch.groovy should stay behind the scene.

This is what I meant by `drop`.

**Comment by romani** [comment]
> diff.groovy to specify this type of run like --patchOnly

this is nonsense, no matter what is a reason behind.

If you are ready for big changes..... : 
1) we should have only only groovy script that we recommend users - new `cs-tester.groovy` (or any other name)
2) launch.groovy should NOT be present in readme
3) cs-tester will have two modes "mode=diff|single"
4) maven should generate for us checkstyle XML report and xref files , we do our own logic to make it in HTML in form that we like(with all details that we need).

**Comment by MEZk** [comment]
@romani 
With all the changes suggested I'm afraid that the script will become too big and difficult to understand. We might need to switch to Java and implement checkstyle-tester as a single jar or try simplify the script logic somehow.

**Comment by romani** [comment]
@MEZk ,
the most complicated is point 4, does it make sense to do 1-3 , and postpone 4 till better time.

**Comment by MEZk** [comment]
@romani 
Yes. it makes sense. Are still insist on merging launch.groovy functionality into diff.groovy?

**Comment by romani** [comment]
lets finish this issue as it is.
I will create new issue to merge groovy scripts.

**Comment by romani** [comment]
new issue #221 .

**Comment by rnveach** [comment]
@romani I think we should re-open this as we still need changes in `diff.groovy` to use changes that were merged for `patch-diff-report`.

**Comment by romani** [comment]
I presume it is fixed
