### ISSUE TITLE
launch.groovy: can't handle reports with links all on 1 line

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#219]
Identified at https://github.com/checkstyle/checkstyle/pull/4236#issuecomment-297380288 : 

Groovy script is removing all `xref` files from user's report.
When debugging the issue I see that the method, `getFilesReferencedInReport` at https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/launch.groovy#L262-L274 , is only getting one result and it is a combination of file and HTML. Each result should be just the file and not any HTML.

The issue is all the user's links are on one line and groovy is written expecting links on separate lines.

Example:
https://github.com/Kietzmann/Kietzmann.github.io/blob/master/openjdk9/site/index.html#L71

Adding a system out to `getFilesReferencedInReport` produces this one, incorrect result:
````
Removing non refernced xref files in report ...
xref/openjdk9/src/jdk.internal.le/share/classes/jdk/internal/jline/TerminalFactory.html#L156">156</a></td></tr><tr class="a"><td><img src="images/icon_warning_sml.gif" alt="" />&#160;Warning</td><td>whitespace</td><td>NoWhitespaceAfter</td><td>'::' is followed by whitespace.</td><td><a href="./xref/openjdk9/src/jdk.internal.le/share/classes/jdk/internal/jline/TerminalFactory.html#L157">157</a></td></tr></table></div><div class="section"><h3 id="openjdk9.test.sun.security.krb5.auto.principalProperty.PrincipalSystemPropTest.java">openjdk9/test/sun/security/krb5/auto/principalProperty/PrincipalSystemPropTest.java</h3><table border="0"class="bodyTable"><tr class="b"><th>Severity</th><th>Category</th><th>Rule</th><th>Message</th><th>Line</th></tr><tr class="a"><td><img src="images/icon_warning_sml.gif" alt="" />&#160;Warning</td><td>whitespace</td><td>NoWhitespaceAfter</td><td>'::' is followed by whitespace.</td><td><a href="./xref/openjdk9/test/sun/security/krb5/auto/principalProperty/PrincipalSystemPropTest.html
````

**Comment by MEZk** [comment]
@romani @rnveach 
I'm on it.

**Comment by romani** [comment]
as we come to idea that default HTML report from maven plugin is not enough for us, we need to start thinking on depending on XML report only and generate HTML in form that we need. Any further updates for HTML rendering in plugin will damage our tool.

**Comment by MEZk** [comment]
@romani 
Let's discuss that in the scope of separate issue. Now we have the issue in launch.groovy. Let's fix it ASAP to avoid contributors confusion.

**Comment by rnveach** [comment]
Fix is merged
