### ISSUE TITLE
merge diff.groovy and launch.groovy

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#221]
base on  https://github.com/checkstyle/contribution/issues/213#issuecomment-297531342

it is hard for contributors to get to know how to run regression in mode then smth new is introduced.
We added special mode to diff.groovy to run only on patch.

We need to have only one tool - cs-tester.groovy that will do all modes of testing. Only this tool is referenced in README

**Comment by rnveach** [comment]
> We added special mode to diff.groovy to run only on patch.

@romani This mode was **NOT** added to `diff.groovy`.
Only changes were added to `patch-diff-report`.
PR #215 started this, but it was put on hold for changes in `patch-diff-report`.

**Comment by MEZk** [comment]
@romani 
Lets do this task after https://github.com/checkstyle/contribution/issues/182. diff.groovy became 'dirty'.

**Comment by romani** [comment]
ATTENTION: we need to be accurate with such merge, for now user experience to run regression on new Check is terrible, example - https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/605#issuecomment-361434841 . The way to launch `diff.groovy` is far from trivial and intuitive.

**Comment by rnveach** [comment]
> user experience to run regression on new Check is terrible

I am not sure why you say it is terrible.
Diff groovy contains a `single` mode which is what is suppose to be used for new checks. All it requires is to add `-diff single` to the end and not specify the base branch/config.
Maybe we should make a section explaining it for new versus old modules?

> sevntu-checkstyle

Sevntu is a different problem all together, as the scripts don't support it at all.
I don't see this as an example that user experience is horrible for the script. We have quite a few successful runs from new people in checkstyle repository.

**Comment by romani** [comment]
I personally use launch model at my company to make a report of new Check( and sevntu too) introduction to a project to generate report to fix, before we actually activate new Check. It is very basic approach, so during merge we just need to make it "same" simple to use and do documentation.

What I do not liked in provided example is that user used another Check in configuration:
```
ThrowsCount|max 20000000|max 20000000
-- | -- | --
ForbidCertainMethodCheck |   | argumentCount 1methodName ^assert(True\|False)$
```

**Comment by rnveach** [comment]
> I personally use launch model at my company

Why don't you use `diff` or `launch`?  Is seeing the parse exceptions the main reason? Like I said, diff's mode of basically only running launch is to add `-diff single`. `diff` script will provide more counts then `launch`'s report.

> What I do not liked in provided example is that user used another Check in configuration

This was only way to remove the parse exceptions which you and him didn't want to see. I have no problem with them being in the report for single modes as they are few.

**Comment by romani** [comment]
@rnveach ,

> Like I said, diff's mode of basically only running launch is to add -diff single
...
This was only way to remove the parse exceptions which you and him didn't want to see. 

diff.groovy ignores "excludes", and this is conceptual difference with launch.
Does it make sense to do NOT ignore excludes in mode `-diff single`  ?
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L190

**Comment by rnveach** [comment]
> Does it make sense to do NOT ignore excludes in mode -diff single ?

Yes, it does make sense for filesets/checks and above. You may want to see parse exceptions if you are adding a new parser like TreeWalker or JavadocParser.
I will open an issue on it.

**Comment by rnveach** [comment]
#529 is closed, so I am going to close this as well
