### ISSUE TITLE
patch-diff-report-tool: Unique rows is not clear

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#222]
patch-diff-report-tool

https://subkrish.github.io/ExplicitInitialization/onlyObjectReferences/RxJava/index.html

```
Summary:
Report id 	Files 	Unique rows 	Severity-warning
base 	409 	113 	113
patch 	409 	18 	18
difference 	62 	95 	95

Number of unique base messages reported below: 95
Number of unique patch messages reported below: 0
```

Unique rows  in patch - 18 , is read as 18 items in green color will be below, but it is not  as amount of item should be read from "Number of unique patch messages reported below"

Question: why we need unclear term ? what is a benefit of it ?

**Comment by rnveach** [comment]
> Unique rows in patch - 18 , is read as 18 items in green color 

This is incorrect.
18 is total number of violations in patch report. This is not directly related to any number of violations in the final report.
Same with 113 is the number of violations in base report.

> Question: why we need unclear term ?

Which term is unclear? "Unique rows"? We could rename it to "Violations".

**Comment by romani** [comment]
lets rename "Unique rows" to "Violations".

**Comment by romani** [comment]
hmmm, one more issue ... .why file difference is 62 ? if base and patch are 409 files ?

**Comment by rnveach** [comment]
> why file difference is 62 ? if base and patch are 409 files ?

This number is based on the number of files we have violation difference records for. https://github.com/checkstyle/contribution/blob/master/patch-diff-report-tool/src/main/java/com/github/checkstyle/data/DiffReport.java#L143

The same behavior can be seen in the tests: https://github.com/checkstyle/contribution/blob/master/patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html#L226
Base and patch files are 9, but difference files is 8.
Files involved in the difference count are: BaseOnly1.java, BaseOnly2.java, Change1.java, Change2.java, Change3.java, Change4.java, PatchOnly1.java, PatchOnly2.java
File missing from the difference count is: Same2.java
It has the same violation in both reports, so it is not a difference and so not included in the difference count.

**Comment by rnveach** [comment]
> lets rename "Unique rows" to "Violations".

Look at header before first violation. https://subkrish.github.io/ExplicitInitialization/onlyObjectReferences/RxJava/index.html#A1
I think we should rename this header from "Unique Rows:" to "Violation differences".
You agree?

**Comment by romani** [comment]
Yes.

**Comment by romani** [comment]
Fix is merged
