### ISSUE TITLE
patch-diff-report-tool: retain special characters in message

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#234]
In preparation for https://github.com/checkstyle/checkstyle/pull/4371#issuecomment-304128792 ,

Exceptions in report don't retain new line characters into the display of the report, so it makes reading a stack trace a little bit harder.

We should convert `\n` into `<br />` to make the stack trace a little easier to read.

Are there any other characters we should retain that aren't like tabs?

**Comment by romani** [comment]
Fix is merged
