### ISSUE TITLE
Revert commits should not be present in release notes

### ISSUE THREAD

**Issue by MEZk** [checkstyle/contribution#236]
Commit https://github.com/checkstyle/checkstyle/commit/5e992cc2369bf314b1d59e34c80fae365c755ef0 and the commit it refers to should be skipped during release notes generation.

Checkstyle 7.8 release notes contains the commit:
https://github.com/checkstyle/checkstyle/commit/c05e29e4d7fa3a0f9a32605cb24b2d721509f46b#diff-2dcbaecbcbd118f0ce9e67aa766b273eR103

I think, that all commits which start with ```Revert ...``` should be omitted in release notes.

**Comment by rnveach** [comment]
@MEZk It looks like we already have this.
See https://github.com/checkstyle/contribution/blob/f15f7aefa005fea42d565bbfb7eeef168b6f414b/releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java#L165 .

So the question is why didn't it work in this instance.

**Comment by romani** [comment]
that revert was mess from my side, I did it incorrectly (I did extra message changes that might mislead algorithm).

**Comment by rnveach** [comment]
@romani Why don't we change it to accept all commits starting with revert? We don't use it any other time.

**Comment by MEZk** [comment]
The logic which decides whether to skip commits which start with "Revert" is incorrect. It should skip commits that start with "Revert" word. Thus, the issue need to be fixed.

**Comment by MEZk** [comment]
The problem is [here](https://github.com/checkstyle/contribution/blob/f15f7aefa005fea42d565bbfb7eeef168b6f414b/releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java#L180-L183). lastSpaceIndex is greater than lastPeriodIndex. The check (lastSpaceIndex > lastPeriodIndex) was done intentionally. 

The correct structure of revert commit is:

```
Revert "config: bump maven-surefire-xxxxxx to 2.20" due to unstable locale UTs #4316
This reverts commit 69a1335.
```

Normally lastSpaceIndex < lastPeriodIndex and SHA-1 of the commit which is reverted is extracted correctly, however, as @romani changed the revert commit message manually, the release notes generator was not able to extract SHA-1 of the reverted commit.

@romani 
Do we need to skip all commits which start with "Revert" ?

**Comment by romani** [comment]
we should skip only if revert and initial commit is matching. I did a mistake, tool was right in his implementation.
Lets not change anything, reverts should happen very rarely.

**Comment by MEZk** [comment]
@romani 
Ok, I'm closing the issues as the original problem was cause by the manual change in the revert commit message. If the revert commit message is changed manually and do not correspond to the standard revert message which is generated by git, the tool will not skip the revert commit.
