### ISSUE TITLE
patch-diff-report-tool: text compare mode

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#239]
Going with discussions at https://github.com/checkstyle/contribution/issues/237 and new regression process talked about at https://github.com/checkstyle/contribution/issues/237#issuecomment-305376062 , we need to make changes to accomplish a new type of file reading and comparing in our difference report.

We need to be able to compare raw files, with no defined layout, and compare them between base and patch for differences.
In the new process, the files we will be comparing are the `.javadoc` files created by a new bash script.

We need a new command line option called `compareMode`. It will allow the options `xml` (default) and `text`.

`xml` will be current process of reading XML file produced by checkstyle and producing differences from that.

`text` mode will scan base/patch directories for all files.
If the same file exists in both, we will use JGit's compare functionality to find differences and print each line of difference to report. Since it is JGit, it will be like looking at changes in a commit, but for our difference reports.
If file doesn't exist in base/patch, we will print a difference stating that.

I feel the current layout of the report already works well for text mode difference viewing, we might just need to make some small adjustments.
Title and first paragraph needs to be different between the 2 modes.
`Rule` could be changed to `Source` to be more generic between the 2 modes.
All severities in text mode could be `difference` or we can drop the column completely.
All column numbers in text mode will always be 0.

Why JGit?
It already has a built-in compare functionality between 2 files which we can try and make use of. I am already familiar with using it for external, custom purposes.
Example:
````
		if (diffAlgorithm == null) {
			diffAlgorithm = DiffAlgorithm.getAlgorithm(SupportedAlgorithm.HISTOGRAM);
		}

		return diffAlgorithm.diff(RawTextComparator.DEFAULT, new RawText(file1), new RawText(file2));
````
We may be able to use it to accomplish Issue #186 too.

Here is a working version with an example compare and it's results:
https://github.com/rnveach/contribution/commits/text_comparing
https://github.com/rnveach/contribution/commit/d99b4090e75109a73f7febcae1717fc85c009178

Example report:
https://github.com/rnveach/contribution/commit/d99b4090e75109a73f7febcae1717fc85c009178#diff-167fa2d3d0dd38139b39b879779b5941

Let me know if this is ok and if I should continue with a PR.

**Comment by romani** [comment]
looks like resolved
