### ISSUE TITLE
releasenotes-builder: Extra "\n" in release notes generations

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#243]
https://travis-ci.org/checkstyle/checkstyle/jobs/237007609 look at raw log

it force me to extra updates to notes to copy them posts or xdoc or .....

**Comment by Vladlis** [comment]
@romani 
your link gives me
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>30</X-Amz-Expires>
<Expires>2017-06-03T20:50:39Z</Expires>
<ServerTime>2017-06-04T18:12:42Z</ServerTime>
<RequestId>ECE0674480B81BC0</RequestId>
<HostId>XX/BIdZJh0Rq5Yg77XYoqvoAtiDqVJeBZaHtThEroSFXOCfb8erzLaSrwufEhEFdrO2XM8gyKW4=</HostId>
</Error>
```

**Comment by romani** [comment]
The same it gives to me now, I updated link in description to Travis logs, looks like raw log link is not persistent

**Comment by MEZk** [comment]
@romani 
Thymeleaf is sensitive to lines formatting. [This](https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_thymeleaf.template#L7) line should have the same line number as the previous one. We will continue getting similar issues till we move to freemarker.

**Comment by romani** [comment]
Please convert us to freemarker, this task is not for Thymeleaf

**Comment by MEZk** [comment]
Switch to the freemarker will be done in the scope of https://github.com/checkstyle/contribution/issues/212

**Comment by romani** [comment]
@MEZk , I do think that we should use only freemarker for this file generation.
It was my design mistake to try to use thymeleaf for xdoc.
thymeleaf is good for html files, that helps to keep template looks well in browser, and result page rendering is well, nobody care about clear html code.
Xdoc - is XML file with script formatting of code, so freemarker is better tool by design for this task.
