### ISSUE TITLE
Add commit hashes and messages to regression reports

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#249]
As discussed at https://github.com/checkstyle/checkstyle/pull/4451#issuecomment-311337578 ,

PR was accidentally merged before regression reports were produced.
Now we must run regression with code already in master, but groovy scripts use master by default. If scripts are used as is, no matter what kind of code changes were done, reports will show no changes. So how can we confirm if there was actually no changes made by PR or it is no changes because PR is comparing itself?

I think we should add commit hashes and messages to the main index of the report, so we can verify what commits the reports are running against.

**Comment by MEZk** [comment]
@rnveach 
If this issue does not require further work, please close it.

**Comment by rnveach** [comment]
Fix was merged
