### ISSUE TITLE
releasenotes-builder: the same author appear multiple times

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#252]
http://checkstyle.sourceforge.net/releasenotes.html#Release_8.0

the same author appear multiple times:
`pitest: increase mutation coverage for pitest-checkstyle-utils profile to 100%. Author: vasilyeva, vasylieva #4395`

**Comment by MEZk** [comment]
It is not an issue. Check the author name. There are two different author names.

**Comment by rnveach** [comment]
vas**ily**eva
vas**yli**eva

I have noticed another contributor have different push names like  sagar-shah94/sagarshah94.
