### ISSUE TITLE
releasenotes-builder: there is problem on Travis to fush output 

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#254]
it is not rare case when build is failing https://travis-ci.org/checkstyle/checkstyle/jobs/253921585 but there is no details on failure, it is started recently(about a month)

tail of log file is:
```
[WARN] Issue #4708 "idea: second part of violations" is not closed!
[WARN] Issue #4711 "idea: code style violations" is not closed!
[WARN] Issue #4394 "pitest: increase mutation coverage for pitest-checkstyle-api profile to 100%" is not closed!
[WARN] Issue #4707 "idea: abstraction violations" is not closed!
[WARN] Issue #4592 "Split BaseCheckTestSupport into AbstractPathTestSupport, AbstractModuleTestSupport, and AbstractTreeTestSupport" is not closed!
[WARN] Issue #4681 "review all suppressed IntellijIdea inspections with comment 'till ...'" is not closed!
[WARN] Issue #4675 "pitest: increase mutation coverage for pitest-checks-misc profile to 100%" is not closed!
[WARN] Issue #4398 "pitest: increase mutation coverage for pitest-checkstyle-tree-walker profile to 100%" is not closed!
[WARN] Issue #4399 "pitest: increase mutation coverage for pitest-checkstyle-main profile to 100%" is not closed!
[WARN] I
```

There is some ERROR in validation that result in error exit code that stop whole shell processing, but looks like jvm output is not flushed and partly lost.

Workaround: 
run it on local, or try to find from recent commits, what issue is missing labels.

This particular problem was in missed label of https://github.com/checkstyle/checkstyle/issues/3301.
Fixed a label.
I will not relaunch build on Travis to keep it in history.

**Comment by rnveach** [comment]
@romani is this still an issue?

**Comment by romani** [comment]
usually we resolve this by "sleep 5" to let travis flush all buffers before it stops execution.

I do not see such hack at https://github.com/checkstyle/checkstyle/blob/master/.ci/travis/xtr_releasenotes-gen.sh#L45

lets close issue for now, ones it come back we can reopen
