### ISSUE TITLE
patch-diff-report-tool: print module ID if it is defined

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#256]
https://github.com/checkstyle/contribution/blob/master/patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/CheckstyleConfigurationsParser.java#L175
```
        String childModuleName = null;
        final Iterator<Attribute> attributes = startElement
                .getAttributes();
        while (attributes.hasNext()) {
            final Attribute attribute = attributes.next();
            if (attribute.getName().toString()
                    .equals(NAME_ATTR)) {
                childModuleName = attribute.getValue();
            }
        }
        final ConfigurationModule childModule =
                new ConfigurationModule(childModuleName);
```

If in config ID is defined, we should use ID of module.
Example of module ID - https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L276
```
    <module name="ReturnCount">
      <property name="id" value="returnCountMaxOne"/>
      <property name="max" value="1"/>
    </module>
```
Current report with multiple of same modules:
![image](https://user-images.githubusercontent.com/812984/28740805-85a5fa00-73be-11e7-9b32-d500b134c4e3.png)

**Comment by rnveach** [comment]
> `<property name="id" value="returnCountMaxOne"/>`
`<property name="max" value="1"/>`

Property IDs are defined exactly the same as normal properties. `patch-diff-report-tool` should already support them in configuration display. It doesn't display them in the summary (violations) as this a limitation of current checkstyle.
The report in the screenshot did not define IDs as I didn't feel it was required for regression.

**Comment by rnveach** [comment]
@romani I am closing this as I was able to confirm locally that `id`s will show up in the report.
Checkstyle was also updated that ids are now shown as the violation source, so you will see them under `Violations` area too.

You can see this locally if you change `InputBaseConfig.xml` and run the tests associated to it in `MainTest`.
