### ISSUE TITLE
Checkstyle-tester: incorrect work launch.groovy for Windows

### ISSUE THREAD

**Issue by sergileon** [checkstyle/contribution#265]
I generated report uses diff.groovy, but it uses [https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L190](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L190). [Launch.groovy](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/launch.groovy#L243) uses a method `getFilesReferencedInReport` that returns HashSet with incorrect paths for Windows. Windows uses "\\" for path, but method return "/".
Screenshot in debug:
![1232313123](https://user-images.githubusercontent.com/19771549/30421661-1f729c04-9946-11e7-9066-7dd4150df010.png)

**Comment by romani** [comment]
@rnveach , please take a look. 
Strange that it worked before, there were bunch of contributors with Windows who generated correct reports.

**Comment by sergileon** [comment]
@romani , now I description the principle work generated report. If I'm wrong, correct me, please. In begin call method [generateCheckstyleReport](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L28). Inside, call [launch.groovy](https://github.com/sergileon/contribution/blob/master/checkstyle-tester/diff.groovy#L190). After, `launch.groovy` generated report and clear folder [src/main](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/launch.groovy#L87)
Generated report contain file `checkstyle-result.xml`.
Example  `checkstyle-result.xml` on Windows:
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="8.3-SNAPSHOT">
<file name="D:\project\check\contribution\contribution\checkstyle-tester\src\main\java\guava\guava\src\com\google\common\annotations\Beta.java">
</file>
<file name="D:\project\check\contribution\contribution\checkstyle-tester\src\main\java\guava\guava\src\com\google\common\annotations\GwtCompatible.java">
</file>
<file name="D:\project\check\contribution\contribution\checkstyle-tester\src\main\java\guava\guava\src\com\google\common\annotations\GwtIncompatible.java">
</file>
<file name="D:\project\check\contribution\contribution\checkstyle-tester\src\main\java\guava\guava\src\com\google\common\annotations\package-info.java">
</file>
<file name="D:\project\check\contribution\contribution\checkstyle-tester\src\main\java\guava\guava\src\com\google\common\annotations\VisibleForTesting.java">
</file>
<file name="D:\project\check\contribution\contribution\checkstyle-tester\src\main\java\guava\guava\src\com\google\common\base\Absent.java">
</file>
....
....
```
But!!! In current moment, `checkstyle-tester\src ` is empty after running `launch.groovy`. After ending `launch.groovy`  the `diff.groovy` call method [generateDiffReport](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L32) which call `patch-diff-report-tool` with argument [patchReport](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L226).
User not see error, because exception is [skipped](https://github.com/checkstyle/contribution/blob/master/patch-diff-report-tool/src/main/java/com/github/checkstyle/site/XrefGenerator.java#L149)

**Comment by romani** [comment]
@sergileon , can you send PR with fix ? As you already debuged this issue. I do not have Windows to verify.

**Comment by rnveach** [comment]
@romani I can atleast confirm that running the regression like
`groovy diff.groovy --localGitRepo C:\projects\checkstyle --mode single --patchBranch master --patchConfig my_check.xml --listOfProjects projects-to-test-on.properties`
results in a report with no xrefs if there are violations.
I have not looked into it more than that.

> Windows uses "\" for path, but method return "/".

Windows should still work fine with `\`, atleast if it is a full path. I would think relatives should work too as long as it doesn't start with `\\` as it will assume it is a SMB drive.
