### ISSUE TITLE
diff.groovy: single mode should not ignore excludes by default

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#278]
https://github.com/checkstyle/contribution/blob/5ecf164754dad43f7a791ec397969a9d795ae63a/checkstyle-tester/diff.groovy#L190

In single difference mode, we should honor excluded files. It is not ideal to show parse exceptions on illegal files as it distracts reviewers from violations/exceptions of the module they are trying to verify.

**Comment by romani** [comment]
>We should have another option only for single mode difference mode that allows us to again ignore excludes if we wish to check new parsers. Honoring excluded files should be the default.

Let's move this to separate issue, as new parser is very unlikely scenario, and for such very rare case we can reuse diff.goovy

It is better to make this issue asap and start deprecation of launch.groovy.

**Comment by rnveach** [comment]
Done.

**Comment by rnveach** [comment]
@romani Is this still needed? We now have the option `allowExcludes` which allows us to turn this on and off at our discreation.

**Comment by romani** [comment]
I think we have all required for all our common cases of usage. This issue is up to you.
