### ISSUE TITLE
diff.groovy: option for single mode to ignore excludes again

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#279]
Based on conversation at https://github.com/checkstyle/contribution/issues/278 ,

Once the other issue is implemented, we should also have another option only for single mode difference mode that allows us to again ignore excludes if we wish to check new parsers. Honoring excluded files should be the default.

**Comment by rnveach** [comment]
@romani Is this still needed? We now have the option `allowExcludes` which allows us to turn this on and off at our discretion.

**Comment by romani** [comment]
up to you.... I think we are ok without this.
