### ISSUE TITLE
releasenotes-builder: revert detection does not work again

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#289]
from release notes of 8.9 release:
```
          <li>
            Revert "config: update to 8.8.1-SNAPSHOT". Author: Roman Ivanov
          </li>
          <li>
            Revert "doc: add release notes for 8.8.1". Author: Roman Ivanov
          </li>
          <li>
            doc: add release notes for 8.8.1. Author: Roman Ivanov
          </li>
```

both reverts should be skipped.

**Comment by rnveach** [comment]
commit message is full message.
https://github.com/checkstyle/contribution/blob/b0220f7b5e9b195ff8fc91bcaec7bff5fac27e3a/releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java#L182-L183

Full message of commits is `Revert "config: update to 8.8.1-SNAPSHOT"

This reverts commit f1d4af3.`.

It is probably failing to find the last `"` at the end of the message at https://github.com/checkstyle/contribution/blob/b0220f7b5e9b195ff8fc91bcaec7bff5fac27e3a/releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java#L169 .

**Comment by rnveach** [comment]
@romani I assume you see no problem with my post?

**Comment by romani** [comment]
Yes, issue just need to be fixed

**Comment by rnveach** [comment]
Fix was merged
