### ISSUE TITLE
releasenotes-builder: provide link to specific commit

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#292]
For those of us more familiar with checkstyle's code, I would like to see a link to the github commit the item is for to see the specific changes involved. Sometimes the issue title isn't clear enough to know what is exactly going on.
The commit can be tracked down through the issue, but it would be easier just to have the direct link on the page instead of going through what is sometimes messy issues.

Example:
`NoWhitespaceAfter: do not allow whitespace after '@' sign. Author: Ruslan Iagudin #4410`

While this is under `new`, so it might be a new token to the check, it doesn't specify what the token name is for users to add, or if it was added to default/required or is only acceptable.

In this example, I would like to see:
`NoWhitespaceAfter: do not allow whitespace after '@' sign. Author: Ruslan Iagudin #4410 (commit)`
Where commit is a link to `https://github.com/checkstyle/checkstyle/commit/3be76368423001233ae7d05235527213bf66ee34`.

If an issue had multiple commits, I would like to see `(commit 1, 2, ` etc...

**Comment by romani** [comment]
I do not think this is good idea, I try to keep release notes as compact as possible.
Engineers who need details will easily find all required information.
