### ISSUE TITLE
releasenotes-builder: allow other repositories

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#309]
Talked about at https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/638#issuecomment-357542972 ,

We should remove any `checkstyle` hardcoding and allow other repositories, like sevntu, to use our tool to build their release notes.

First change I see we needing is to remove
https://github.com/checkstyle/contribution/blob/d9836c08428486e758d6950bf972256e60859171/releasenotes-builder/src/main/java/com/github/checkstyle/Main.java#L45-L46
And allow users to specify remote github location through CLI.

**Comment by romani** [comment]
@rnveach , releasenotes generation process is very different from project to project.
What if we will move required parts to util methods(or smth another ....) to be reused in new builder ?

**Comment by rnveach** [comment]
Right now my main aim was HTML release notes with links to issues and type of change.

> releasenotes generation process is very different from project to project.

Can you give more specific scenarios? You can use checkstyle and sevntu.

**Comment by romani** [comment]
I am ok with all changes.

**Comment by rnveach** [comment]
Talked about at https://github.com/checkstyle/contribution/pull/310#issuecomment-399729915 ,

we need an extra options to allow user to supply custom xdoc template and custom xdoc location.

**Comment by rnveach** [comment]
sevntu used release notes just fine, so I am closing this issue as I don't see anything else to add.
