### ISSUE TITLE
releasenotes-builder: html content is not escaped

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#311]
Generated chunk of html
```
          <li>
            http://checkstyle.sourceforge.net ==> http://checkstyle.org. Author: Roman Ivanov <a href="https://github.com/checkstyle/checkstyle/issues/5601">#5601</a>
          </li>

```

problem is at `==>`, all content should be escaped.

**Comment by rnveach** [comment]
What about the mailing lists, rss, twitter, etc?

**Comment by romani** [comment]
> What about the mailing lists, rss, twitter, etc?

it works fine for them, no escaping is required.

**Comment by romani** [comment]
fix is merged
