### ISSUE TITLE
releasenotes-builder: line is too long

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#312]
content:
```
          <li>
            Generate a suppressions.xml file for SuppressionXpathFilter from the errors list by CLI command. Author: timurt <a href="https://github.com/checkstyle/checkstyle/issues/102">#102</a>
          </li>

          <li>
            doc: update xdoc for ParameterName to clarify how to check catch parameters. Author: Roman Ivanov
          </li>
```

build failure:
`[checkstyle] [ERROR] .....checkstyle/checkstyle/src/xdocs/releasenotes.xml:74: Line should not be longer then 100 symbols [RegexpSingleline]`

Failure is because line is without web link.

probably we need to generate content like (line were cut to satisfy line limit):
```
          <li>
            Generate a suppressions.xml file for SuppressionXpathFilter from the errors 
            list by CLI command.
            Author: timurt
            <a href="https://github.com/checkstyle/checkstyle/issues/102">#102</a>
          </li>

          <li>
            http://checkstyle.sourceforge.net to http://checkstyle.org.
            Author: Roman Ivanov
            <a href="https://github.com/checkstyle/checkstyle/issues/5601">#5601</a>
          </li>
```

**Comment by rnveach** [comment]
1)
Does it matter if the breaking looks like this?
````
          <li>
            Generate a suppressions.xml file for SuppressionXpathFilter from the errors 
list by CLI command.
````

We can probably break the message up, but indenting may not be done by freemarker. I am not finding anything on a quick google search. We can always hardcode the indenting in the code.

2)
What rules do you want for breaking a line?

Always break by space first.
If no space and word is longer then X characters (100 in this case), break by 99 and append `-` to the end.

3)
Should we be worried about breaking author name?

**Comment by romani** [comment]
>1

It is ok

>2

If word is long - by space before it

>3

Author on separate line no breaks, should work fine for most cases.

**Comment by romani** [comment]
Fix is merged

**Comment by romani** [comment]
https://travis-ci.org/checkstyle/checkstyle/jobs/400502532#L849

only html should be affected, but all other generations are affected too.

looks bad:
```
New:
  ImportOrder: new property groupsStatic to allow define groups for
static imports
Bug fixes:
  EmptyLineSeparator raises violations when static import right after
plain import
Notes:

```

**Comment by rnveach** [comment]
Full regression also found another issue that our tests missed:
https://travis-ci.org/checkstyle/checkstyle/jobs/400502532#L750
https://travis-ci.org/checkstyle/checkstyle/jobs/400502532#L757
Remote repo path and release number are swapped.

I will add fuller regression first before fixing these issues.

**Comment by rnveach** [comment]
> Remote repo path and release number are swapped.

This was fixed with the following:
https://github.com/checkstyle/contribution/pull/328/files#diff-1878023d96b22097ab9757f59dfdceeeL168
https://github.com/checkstyle/contribution/pull/328/files#diff-8e0f717ac6e842c752b20bac04690847R99

> only html should be affected

This has not been fixed yet.

**Comment by romani** [comment]
Fix is merged

**Comment by romani** [comment]
Here is build of release notes based on this fix https://travis-ci.org/checkstyle/checkstyle/jobs/510224144 we need to check no line wrap in text notes

**Comment by romani** [comment]
There was still extra line wrapping in release notes 8.19, I manually corrected them in my commit.

**Comment by rnveach** [comment]
@romani Can you be more specific.
Here is the travis job: https://travis-ci.org/checkstyle/checkstyle/jobs/513774164

**Comment by romani** [comment]
Example from tool output:
```
Remove DTDs from http://checkstyle.sourceforge.net and from
http://puppycrawl.com/.
```
I removed extra line wrapping https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/releasenotes.xml#L34

**Comment by rnveach** [comment]
This separation is still in xdoc. I thought originally you had a problem with non-xdoc area again.

> Remove DTDs from http://checkstyle.sourceforge.net and from
http://puppycrawl.com/.

According to the split logic at https://github.com/checkstyle/contribution/commit/3a8c11285b15f7b40f441dcb2f495badcd5c81f3#diff-31866b0f9e80d9bf93fce3e5da8dfb17R31 , we will split a line if it is more then 70 characters long.
`Remove DTDs from http://checkstyle.sourceforge.net and from` == 60 characters
`http://puppycrawl.com/.` == 24 characters and no whitespace

Since 60+24 = 84 which is >70, and since there is no whitespace, the system split the line into 2.

13 spaces are appended to first line because of indentation, so we chose 70 as a safer amount to split on then looking to reach perfect 100 characters.

If you are not satisfied, then the 70 character limit can be changed, otherwise the logic looks to be working correctly to me.
