### ISSUE TITLE
releasenotes-builder: allow templates to print todays date

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#320]
Checkstyle and Sevntu want a way to print the date of the release.
Example: http://sevntu-checkstyle.github.io/sevntu.checkstyle/#1.29.0

We should allow the templates to print today's date like `${todaysDate}`.
No CLI options are needed, just always use the current date. Both will just have to use the same date formatting.

**Comment by rnveach** [comment]
@romani I have the fix ready to go, and have screenshot examples of checkstyle's release notes, but how do we do date testing?
Our test files are static. Should I just do a replace on the contents of the file for the dynamic value or is there a better way?

**Comment by romani** [comment]
We need make template be smart and put date only if some flag defined. So all static UT will have such feature disabled.

Is it doable ?

**Comment by rnveach** [comment]
Fix was merged.
We still need additional changes in both repos.
