### ISSUE TITLE
releasenotes-builder: add better in-depth tests

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#327]
We need few tests for parsing and creation of release notes content that is based on Github issue titles that are referenced in commits.

**Comment by romani** [comment]
@rnveach , do you want to add more tests ?

**Comment by rnveach** [comment]
Yes, I want to add some tests for the guy title parsing.

**Comment by romani** [comment]
we can try to use mockserver https://www.mock-server.com/mock_server/running_mock_server.html
to simulate responses from Github api.
1-2 test methods is enough.

I do not think we should deal with real/mock of git repo. we can just simulate that jgit library return us some results that we need.
1-2 test methods is enough.

**Comment by romani** [comment]
several tests were done at https://github.com/checkstyle/contribution/pull/705

@stoyanK7 , to close this issue, please convert existing test for content validation to use this approach of testing.
It will be enough for this issue to be closed.

**Comment by stoyanK7** [comment]
On it.

**Comment by rnveach** [comment]
Fix was merged
