### ISSUE TITLE
Resolve violation from Intellij idea 2018

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#335]
default Idea version is upgraded in TC to 20181.1.4

https://teamcity.jetbrains.com/viewLog.html?buildId=1655102&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsMaster

 Encapsulation
Assignment or return of field with mutable type (Errors) (1)
src/main/java/com/github/checkstyle/globals
 Result.java (1)
73: getReleaseNotes() Return of Multimap<String, ReleaseNotesMessage> field releaseNotes 

 Error handling
Unchecked exception declared in 'throws' clause (1)
src/test/java/com/github/checkstyle/templates
 TemplateProcessorTest.java (1)
308: createReleaseNotesMessage() Unchecked exception SecurityException declared in 'throws' clause 

 Naming conventions
Method naming convention (Errors) (1)
src/main/java/com/github/checkstyle
 MainProcess.java (1)
77: run() 'static' name run is too short (3 &lt; 4) 

 Performance issues
Call to 'Arrays.asList()' with too few arguments (Errors) (5)
src/test/java/com/github/checkstyle/templates
 TemplateProcessorTest.java (5)
141: testGenerateAll() Call to asList with only one argument 
142: testGenerateAll() Call to asList with only one argument 
143: testGenerateAll() Call to asList with only one argument 
144: testGenerateAll() Call to asList with only one argument 
145: testGenerateAll() Call to asList with only one argument 

 RegExp
Single character alternation (3)
src/main/java/com/github/checkstyle/github
 NotesBuilder.java (3)
64:  Single character alternation in RegExp
65:  Single character alternation in RegExp
66:  Single character alternation in RegExp

Verbose or redundant code constructs
Redundant Collection operation (1)
src/main/java/com/github/checkstyle/github
 NotesBuilder.java (1)
330: findCommitAuthors() Unnecessary 'contains' check

Verbose or redundant code constructs
Redundant String operation (2)
src/main/java/com/github/checkstyle/globals
 ReleaseNotesMessage.java (2)
124: split() Call to substring is redundant 
131: split() Call to substring is redundant

**Comment by rnveach** [comment]
Fix was merged
