### ISSUE TITLE
Please do shallow clones in checkstyle-tester when a tag or branch is to be tested

### ISSUE THREAD

**Issue by Vampire** [checkstyle/contribution#351]
When using the checkstyle-tester it would be nice if it would do shallow clones with depth 1 for Git repos if possible.

If I for example do
`git clone https://github.com/google/guava`
the resulting directory is 283 MiB, if I instead do
`git clone --depth 1 --branch v25.0 https://github.com/google/guava`
the resulting directory is 43 MiB.

This saves significant time, bandwidth and disk-space.

**Comment by romani** [comment]
Yes, our test tools have bunch of rooms to improve.
+1.

**Comment by rnveach** [comment]
I'm not sure we can do this without some other breaking change.

> git clone --depth 1 --branch v25.0 https://github.com/google/guava

The field in the property file is `COMMIT_ID`. We cannot really know if it is a branch or a commit hash. Some of our repos use a hash.
I am not seeing a method on git clone to give it a hash, and `--branch` will not work with a hash.
If we use `--depth` by itself, the checkout command will fail saying it can't find the branch/hash.
> fatal: ambiguous argument 'v18.0': unknown revision or path not in the working tree.

**Comment by Vampire** [comment]
> The field in the property file is `COMMIT_ID`. We cannot really know if it is a branch or a commit hash. Some of our repos use a hash.
> I am not seeing a method on git clone to give it a hash, and `--branch` will not work with a hash.
> If we use `--depth` by itself, the checkout command will fail saying it can't find the branch/hash.

Well, we could either change the format of the config file to either have two columns, one for ref names (branches or tags) that will do a shallow clone, one for other commit-ish values that will do a full clone and check out the specified commit-ish. (breaking of course)

Another way without a new column would be to support a prefix in the existing column, e. g. like `ref:v25.0` or `shallow:v25.0`, so that a shallow clone is done if the prefix is present and otherwise do a full clone and check out the specified commit-ish, no matter whether it is a ref or some other commit-ish. (non-breaking backwards compatible but needs explicit config for shallowness)

A third way would be to try a shallow clone and if it fails, do a full clone and check out the specified commit-ish. As the ref is directly searched in the remote repo to only clone that one commit, this will not need too much time in case of failure (non-breaking backwards compatible and automatically working without the need to specify shallowness manually)

> Even if we do do this, if we ever change the branch/commit, we would have to do a shallow fetch. It doesn't look like you can specify branch for a shallow fetch.

Sure you could, for example `git -C guava fetch --depth=1 origin v18.0:v18.0` to shallowly fetch v18.0.
But actually the changing of commit-ish is not really properly supported anyway currently.
On first usage of a repo it is cloned.
After that if the checked out commit is not the wanted commit-ish, only a `reset --hard` is done to the different commit-ish.
So only commit-ishs that are in the original clone are supported.
There is never any fetch done.

And besides that, `reset --hard` is not a good way anyway, `checkout` would be more appropriate.
`reset --hard` also lets the current branch pointer point to the new commit.
So if you have commit-ish `master` and run, then change the commit-ish to `1234abc` and run (assuming the commit is part of the clone), `master` is now pointing to `1234abc` instead, so if you then do `master` again, you won't get the previous commit, but stay on `1234abc`.
Unless you make sure you always work on a detached head, for example by always appending `^0` to the commit-ish that is checked out, or by using `--detach` option. Then `reset --hard` would be equivalent to `checkout`. But even then it would be cleaner to use checkout rather than reset.

> What about #180 and when we specify `master`?

Well, what I just described above :-)
