### ISSUE TITLE
releasenotes-builder: avoid extra line wrapping

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#364]
https://github.com/checkstyle/contribution/issues/312#issuecomment-478472949

It is better to not wrap line if it could fit in line limit 100 symbols per line. Xdoc file has certain indentation that unlikely to change.

Additional minor issue is to trim spaces in front of issue title, it is visible in non xdoc content.

**Comment by rnveach** [comment]
Is it ok to just increase the limit by 10? or you want 17?
original 70 + addition of 10 + 13 indentation spaces gives us a max line of 93.

**Comment by romani** [comment]
it is not a general tool, I am ok with anything, just to avoid manual update of release notes.
I still want to make release + notifications completely automated and not be locked to me.

**Comment by Rahulkhinchi03** [comment]
@romani @rnveach Please confirm the limit of line.

**Comment by romani** [comment]
Line limit is 100.
Any line that is above, should be wrapped with proper indentation.

**Comment by Rahulkhinchi03** [comment]
Just this needs to be changed, right? 
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java#L32 and with this, the template's some minor indentation

**Comment by romani** [comment]
yes, I do not remember why it was set to 70, please test after update, there might be some other change is required also.

**Comment by rnveach** [comment]
> I do not remember why it was set to 70

https://github.com/checkstyle/contribution/issues/312#issuecomment-478472949

**Comment by Rahulkhinchi03** [comment]
@romani @rnveach kindly help with what other changes will be required other than:
https://github.com/checkstyle/contribution/issues/364#issuecomment-1236368780

**Comment by raghav-rama** [comment]
@Rahulkhinchi03 have you resolved the issue?

**Comment by romani** [comment]
Issue is not resolved. You can reuse referenced code as base but it should be further improved. Look at referenced PR.
