### ISSUE TITLE
New check: Jsr305Annotations

### ISSUE THREAD

**Issue by mbert** [checkstyle/contribution#380]
In the _seventu-checkstyle_ project, PR [#742](https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/742) introduces a new check which is described in detail in issue [#734](https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/734). In order to merge that PR, the file `checkstyle-tester/checks-sevntu-error.xml` needs to be changed here. 

A new PR referring to this issue will be created.

**Comment by romani** [comment]
fix is merged.
