### ISSUE TITLE
checkstyle-checker need to remove non mentioned files in report from xref folder

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#40]
reports could be huge due to huge amount of sources (a lot of projects is used).
But it is rear case when each source file has violation and required to be published with report. 

We need to update checkstyle-checker to remove non used in report(target/site/index.html) files from xref (target/site/xref) folder.

**Comment by romani** [comment]
```
FILES=$(grep xref target/site/index.html | grep -v "xref/index.html" |  sed 's/<td><a href="//' | sed -E 's/\.html#L.*/.java'/ | tr -s "\n" '|' | sed 's/|$//')
cd target/site/xref
 find . -type f ! -name "$FILES" -delete
```
remove all empty folders:
```find . -type d -empty -exec rmdir "{}" \;```

**Comment by romani** [comment]
on guava project with google_checks.xml , no huge difference.

before:
```
du -hs target/site
75M	target/site
```

after : 
```
du -hs target/site
69M	target/site
```

**Comment by romani** [comment]
@rdiachenko  , @baratali  , @mkordas  , @Vladlis  , @MEZk  , @sabaka - please pull latest contribution/checkstyle-checker to minimize size of generated report size.

**Comment by mkordas** [comment]
@romani, I have problems with it on Windows. In one console that I use `find` doesn't support `-delete` while in another `regexp` parameter is buggy when alternative is provided (`|`). Maybe we could do such filtering in Groovy?

**Comment by romani** [comment]
Ok :(, feel free to update.

**Comment by romani** [comment]
@mkordas , please share what consoles you use in Windows and might be link how to install them, I think we need to extend our Appveyor to use checkstyle-tester too, to make sure that any contributor can do fix for a code and test it even on Windows.

**Comment by mkordas** [comment]
I use [MobaXterm](http://mobaxterm.mobatek.net/) and [Git Bash](https://git-for-windows.github.io/). I'm not sure if it is possible to make them working in AppVeyor.

**Comment by romani** [comment]
@rnveach , do you have problems with running checkstyle-tester on your windows ? What bash emulator do you use ?

**Comment by rnveach** [comment]
I do have MinGW and Git Bash installed and have access to ubuntu computers, but I used neither to run checkstyle-tester's sh file. I just manually placed the files and ran the maven command from eclipse.

**Comment by romani** [comment]
@mkordas , @rnveach why you do not use  http://www.cygwin.com ?  Just curious.

**Comment by rnveach** [comment]
It is rare I need to run linux commands on windows. Most of my needs are met by alternatives that are created for windows. I only keep MinGW around for a free, standard C++ compiler, and I am more dependent on Eclipse for Git now. I have never run into a situation where I needed to look at cygwin.

**Comment by mkordas** [comment]
@romani, I'll try with Cygwin. I was using it before, but then I found MobaXterm to be more convenient to install and use, but apparently it has also some problems.

**Comment by romani** [comment]
I got `./launch.sh: line 101: /usr/bin/find: Argument list too long`  during testing , I need to refactor this code

**Comment by romani** [comment]
I simplified removing non referenced files, please try again in your systems, nothing fancy was used, bash is simple.

**Comment by romani** [comment]
@Vladlis , please describe a problem with that force you to do revert and show report that can not be parsed.

**Comment by Vladlis** [comment]
I tried to run the tester on drone.io CI, but faced the following exception [link](https://drone.io/github.com/Vladlis/checkstyle/7):
> Running Checkstyle on src/main/java - finished
linking report to index.html
Removing non refernced xref files in report ...
Backuping files that are refenced in report ...
mv: cannot stat `<div': No such file or directory

The project I ran the tester against is openjdk7 and the config is this file https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/my_check.xml .

Strange, but I could not reproduce the problem on my local PC (even though drone.io uses ubuntu and I run ubuntu-based system).

**Comment by romani** [comment]
Next time please catch a reason of failure on a moment of failure.

For now i close the issue.

**Comment by romani** [comment]
@mkordas , @rnveach , checkstyle-tester works fine on windows Cygwin, now it is in our build system - https://github.com/checkstyle/checkstyle/commit/8cbc23964accf22e2df7aedbc7f7f02f8ad202c3 .

As you can see from commit, Cygwin just need to be installed in default format , additional packages
"C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P autoconf -P automake -P bison -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl" as described at  http://www.appveyor.com/updates/2015/05/30
Launch bash, and just run checkstyle-tester, it should work.

**Comment by Vladlis** [comment]
@romani , to run checkstyle-tester against openjdk mercurial is also required

**Comment by romani** [comment]
It is also installed by additional command, see "install" section in appveyor.yml
