### ISSUE TITLE
patch-diff-report-tol: print case number right aftre `#` 

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#400]
users are sharing a link to certain case like https://strkkk.github.io/4763/checkstyle/index.html#A3

![image](https://user-images.githubusercontent.com/812984/63288569-e1638700-c271-11e9-9235-e702d3037db7.png)

I am always recheck that browser did scrolling to right case.
It would be better for us to print `#A3` in cell of table.

**Comment by romani** [comment]
@rnveach , please review and approve.

**Comment by rnveach** [comment]
Approved.

This repo has no approve label.

**Comment by romani** [comment]
closed in favor of #422
