### ISSUE TITLE
diff report should wrap all long content to looks better on mobile

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#426]
https://gmshake.github.io/checkstyle_contribution/checkstyle-tester/diff_pr_7365_4/checkstyle/index.html
or
https://checkstyle.sourceforge.io/reports/7116-detect-throw/diff/apache-jsecurity/index.html

as diff reports should be reviewed even on the go
it is not very good for mobile :
![image](https://user-images.githubusercontent.com/812984/71226623-69de4c80-2291-11ea-9fa8-d0f245ec8b81.png)

------------

**Better form**:
![Screenshot_2019-12-19 checkstyle xml difference report](https://user-images.githubusercontent.com/812984/71226598-41eee900-2291-11ea-8fad-1667d40637eb.png)

**Comment by rnveach** [comment]
@romani Does this close the issue?

**Comment by romani** [comment]
yes, for now lets close it.

@jo2 , thanks a lot your work.
