### ISSUE TITLE
diff.groovy: add base and patch configs to diff report

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#430]
when config is big (CustomImportOrder) in diff report ... it time consuming to recreate config on local to see full validation output for Input.

we can have link to file at "Base properties" "Patch Properties" headers of table.
![image](https://user-images.githubusercontent.com/812984/71324558-fe64cc80-2494-11ea-8471-00c9a9135ba7.png)

**Comment by rnveach** [comment]
This would just need to be a change in patch-diff-report-tool to add the link to the report and copy the files to the same directory as the report.

**Comment by nmancus1** [comment]
This would be easiest to implement using the code merged in #462, and simply link to the configs in index.html. If we agree, I can submit a PR today.

**Comment by romani** [comment]
Yes, please do simple link, you can make links manually in some report and share with us to make sure we mean the same

**Comment by nmancus1** [comment]
Basic Difference Report
![image](https://user-images.githubusercontent.com/31252532/86145596-1ad96580-bac5-11ea-8d36-e6dded92d187.png)

Difference Report with Different Base and Patch Config
![image](https://user-images.githubusercontent.com/31252532/86150692-ba99f200-bacb-11ea-850c-955aeca91708.png)
Link: https://nmancus1.github.io/diff_base_patch_example/index.html

**Comment by romani** [comment]
we did a workaround solution, later on we can update diff site generator to keep link to raw config close to HTML diff view of it.
