### ISSUE TITLE
diff.groovy: add timestamp to main report next to commit hash

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#431]
Add timestamp to main `diff.groovy` so reviewers can see when the commits being worked with were created. It will be easier than determining how old the commit used is in github's history.

**Comment by rnveach** [comment]
Adding to report:
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L297
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L305

Generating value:
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L194

We just need to add some minor additions to print the timestamp. We should get the timestamp from the commit being used, specifically the committed date.

**Comment by romani** [comment]
Fix is merged
