### ISSUE TITLE
update pmd to latest stable version in all property files

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#456]
from https://github.com/checkstyle/checkstyle/issues/7534

Example:
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L19

update all other property files in same folder if they have pmd referenced.

we need to update PMD to most latest stable version.

**Comment by romani** [comment]
@nmancus1 , please help to resolve this issue.

**Comment by nmancus1** [comment]
I'm on it.

**Comment by rnveach** [comment]
Looks like issue is resolved

**Comment by rnveach** [comment]
I am re-opening this issue as additional fixes need to be made.

**Comment by romani** [comment]
Fixed in https://github.com/checkstyle/contribution/commit/fdc04f5789658cf002832c6eb5ea33ccd1c5b09a
