### ISSUE TITLE
Add information about new/removed violations to main report page

### ISSUE THREAD

**Issue by strkkk** [checkstyle/contribution#461]
Rationale - now, to check number of unique/removed violations, user should click on hyperlink for each project.

Proposal - show this information on main page, add it to existing number of total violations, e.g.
```
android-launcher (total: 42, new: 21, removed: 21)
```
It will make it easier to detect if there is some new violation. It will be very useful in case some check produces a lot of violations and it is difficult to analyze report where each projects has some.

**Comment by rnveach** [comment]
The main reason this was not added to begin with was because of limitations of old shell script way.

Example report:
![regression](https://user-images.githubusercontent.com/5427943/76516240-6e9a4300-6431-11ea-89ca-022024d936e0.gif)

@strkkk I assume in your proposal you just want to bring in numbers from `Number of unique base messages reported below` and `Number of unique patch messages reported below` only and display them as `new` and `removed`?

**Comment by strkkk** [comment]
> I assume in your proposal you just want to bring in numbers from Number of unique base messages reported below and Number of unique patch messages reported below only and display them as removed and new respectively?

Yes, in my mind it is same thing :)

**Comment by rnveach** [comment]
Feel free to start new issues for anything you see. One possible thing to be wary of is too much information on the summary. For example, if we start bringing in counts for all module instances, summary report will become littered with numbers everywhere and may be too hard to find/see the important information.

**Comment by romani** [comment]
@strkkk , before any coding, can you take some heavy report and update report summary (manually) to keep statistics you like on summary page, it will give us good example on how it will looks like.

https://wilcoln.github.io/checkstyle-reports/7723v2/diff/index.html from https://github.com/checkstyle/checkstyle/pull/7792

**Comment by Abhishek-kumar09** [comment]
I am working on it, I think wilcoln had deleted his repo that is mentioned in the comment by Mr. Roman Ivanov.

**Comment by strkkk** [comment]
Fix is merged
