### ISSUE TITLE
diff.groovy: add property file used for testing to report

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#462]
Identified at https://github.com/checkstyle/checkstyle/pull/7852#issuecomment-600138175 ,

update our diff site generation to publish property files to troubleshoot contributors problems easily . This should put up the file passed to the `listOfProjects` argument.

**Comment by nmancus1** [comment]
I think this is a great idea and would like to work on this. Essentially, we want to link to a html page generated from `projects-to-test-on.properties`, from the main report page, right?

**Comment by nmancus1** [comment]
What's the best way to generate the html for this?  Would you like the appearance of the page generated to look like the generated java html files from the reports, with line numbers, etc.?

**Comment by rnveach** [comment]
For debugging it would be useful if there was line numbers and the line numbers were links so we could point to what is wrong. I would use this already built class to display the file, https://github.com/checkstyle/contribution/blob/master/patch-diff-report-tool/src/main/java/com/github/checkstyle/site/TextTransform.java .

**Comment by nmancus1** [comment]
Great!  Thanks for the advice.

**Comment by nmancus1** [comment]
@rnveach This is my first time using groovy, and I'm having a hard time importing TextTransform.  Can you offer any advice?  IDEA is OK with the import, but when I run groovy via command line,  I keep getting: 
`unable to resolve class com.github.checkstyle.site.TextTransform`.

I've tried to specify the classpath when running groovy, and that doesn't help.  I've also tried to just put a copy of the class into the directory with diff.groovy, and still no joy.

**Comment by rnveach** [comment]
> This is my first time using groovy, and I'm having a hard time importing TextTransform. 

My initial thought was to not use groovy for the reports and attach it to the project report and hence integrate with the TextTransform that is part of patch-diff-report-tool.

The issue here is that patch-diff-report-tool is specific to that project and this property file is for the run for the whole report. It does make more sense to attach it to the groovy outside report generation. Problem is we lose access to TextTransform. My knowledge of groovy is limited, but my understanding is we can only import other JARs and not Java files. I don't think we can import class files.

Our choices are:
1) Re-create text-transform as groovy.
2) Drop text-transform and just make it so the raw file is on the report.
3) Have patch-diff-report-tool create the property file duplicating for each report.

First I want to know, can we import the patch-diff-report-tool JAR into groovy (since it is required anyways) and call TextTransform that way?

**Comment by nmancus1** [comment]
We can load the JAR dynamically:

```
  this.class.classLoader.rootLoader.addURL(new URL("file:patch-diff-report-tool-0.1-SNAPSHOT-jar-with-dependencies.jar"))
    def textTransform = Class.forName("com.github.checkstyle.site.TextTransform").newInstance()
```

**Comment by rnveach** [comment]
It looks good to me, please start a PR.

**Comment by romani** [comment]
fix is merged.
