### ISSUE TITLE
Diff Report Generation freezes on including jdk11u or jdk14 projects.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [checkstyle/contribution#483]
I had felt an issue in diff report generation when I include jdk14 or jdk11 projects to test upon in the `project-to-test-on.properties`.
The diff report generation process freezes on 
```
[INFO] Generating "Checkstyle" report    --- maven-checkstyle-plugin:3.1.1

```
and doesn't show progress. I had tried to test again after removing either of projects from testing and it always freezes whenever each of the two project is present.

[Link to problem gist](https://gist.github.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a)

**Comment by pbludov** [comment]
You can use
```
export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=debug
groovy diff.groovy --localGitRepo ...
```
to find the problem.

**Comment by Abhishek-kumar09** [comment]
```bash
[INFO] Generating "Checkstyle" report    --- maven-checkstyle-plugin:3.1.1
[DEBUG] executeCheckstyle start headerLocation : LICENSE.txt
[DEBUG] Added 47806 source files found in '/home/abhishek99/openSource/contribution/contribution/checkstyle-tester/src/main/java'.
[DEBUG] The resources directory '/home/abhishek99/openSource/contribution/contribution/checkstyle-tester/src/main/resources' does not exist or is not a directory.
[DEBUG] No test resources found in this project.
[DEBUG] Added 47806 files to process.
[DEBUG] request.getConfigLocation() my_check.xml
[DEBUG] The resource 'my_check.xml' was not found with resourceLoader org.codehaus.plexus.resource.loader.JarResourceLoader.
[DEBUG] The resource 'my_check.xml' was found as /home/abhishek99/openSource/contribution/contribution/checkstyle-tester/my_check.xml.
[DEBUG] headerLocation LICENSE.txt
[DEBUG] JarResourceLoader : trying to load "jar:file:/home/abhishek99/.m2/repository/com/puppycrawl/tools/checkstyle/8.33-SNAPSHOT/checkstyle-8.33-SNAPSHOT.jar"
[DEBUG] JarResourceLoader : trying to load "jar:file:/home/abhishek99/.m2/repository/com/github/sevntu-checkstyle/sevntu-checks/1.37.1/sevntu-checks-1.37.1.jar"
[DEBUG] JarResourceLoader : trying to load "jar:file:/home/abhishek99/.m2/repository/org/apache/maven/plugins/maven-jxr-plugin/2.5/maven-jxr-plugin-2.5.jar"
[DEBUG] The resource 'LICENSE.txt' was not found with resourceLoader org.codehaus.plexus.resource.loader.JarResourceLoader.
[DEBUG] The resource 'LICENSE.txt' was not found with resourceLoader org.codehaus.plexus.resource.loader.FileResourceLoader.
[DEBUG] URLResourceLoader: No valid URL 'LICENSE.txt'
[DEBUG] URLResourceLoader: No valid URL 'LICENSE.txt'
[DEBUG] The resource 'LICENSE.txt' was not found with resourceLoader org.codehaus.plexus.resource.loader.URLResourceLoader.
[DEBUG] Unable to process header location: LICENSE.txt
[DEBUG] Checkstyle will throw exception if ${checkstyle.header.file} is used
```

**Comment by romani** [comment]
I had only OOM on jdk14.

@Abhishek-kumar09 , if this blocks you for some reports generation, please skip jdk from report and mention this issue in your PR as reason of missed openjdk in report.

**Comment by rnveach** [comment]
Point to the specific project with URL it stalled on.
What was the config you were running with?
Was it stalling on the master run or the PR run?

The last error printed is what comes up in maven-checkstyle-plugin right when it is creating the config, so it seems safe to assume if there is a real stall, and more than just alot of files, it would be in our project.
https://github.com/apache/maven-checkstyle-plugin/blob/eae07f99f01584bfd3da90a8c5eb32364e8ee82b/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L560

**Comment by Abhishek-kumar09** [comment]
@rnveach 
> What was the config you were running with?

[my_check.xml](https://gist.github.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a#file-my_check-xml)

`project-to-test-on`:
```
openjdk11|git|https://github.com/openjdk/jdk11u|master||
openjdk14|git|https://github.com/openjdk/jdk14|master||
**/test/hotspot/jtreg/runtime/records/recordReflectionTest.java - till we support records
**/test/langtools/jdk/javadoc/doclet/testRecordTypes/** - records
**/test/jdk/java/lang/invoke/defineHiddenClass/** - records and other new features
**/test/jdk/java/lang/reflect/records/
**/test/jdk/java/**/records/**
**/test/langtools/tools/javac/** - too much non compilable
**/test/jdk/java/lang/instrument/*Record*/**
**/test/jdk/java/awt/Window/MinimumSizeDPIVariation/** - new syntax - switch
**/test/langtools/jdk/javadoc/tool/** - too much non compilable
**/src/jdk.jshell/share/classes/jdk/jshell/SourceCodeAnalysisImpl.java - looks like a our bug
**/src/java.base/share/classes/sun/security/ssl/SSLSocketImpl.java - our bug
**/src/java.base/share/classes/java/lang/invoke/AddressVarHandleGenerator.java - switch
**/src/java.desktop/share/classes/javax/sound/sampled/AudioFormat.java
```

[Used in PR](https://github.com/checkstyle/checkstyle/pull/8271#issuecomment-636515968)

**Comment by rnveach** [comment]
I will see if I can find anything out, but this is for Indentation. You will need to give regression more memory for Indentation. I usually have to give it 4 gigs. Also regression usually works better if you use the config the project defines, otherwise errors can be confusing.

In the meantime, I would not run regression on those projects with Indentation.

**Comment by rnveach** [comment]
Will update status as I look into the issue.

For me, it seems it is stalling on `openjdk11/test/langtools/tools/javac/lambda/speculative/NestedLambdaGenerics.java`.
https://github.com/openjdk/jdk11u/blob/737d8437886ad97c6ed21a25b9911c10b3886f61/test/langtools/tools/javac/lambda/speculative/NestedLambdaGenerics.java

**Comment by romani** [comment]
@Abhishek-kumar09 , please skip openjdk for Indentation, there will be too much violations, I doubt maven plugin can handle such size.

**Comment by rnveach** [comment]
@romani Why did we close this issue when it is still a problem? I don't think this is related to indentation but our Java parser.

**Comment by rnveach** [comment]
Until https://github.com/checkstyle/checkstyle/issues/8291 is fixed, regression cannot be run on jdk11

**Comment by romani** [comment]
@rnveach , can we exclude single or few files ? To keep running on jdk

**Comment by rnveach** [comment]
Regression was built to never exclude files. You would have to change our tool to have it exclude something now.

**Comment by romani** [comment]
https://github.com/checkstyle/contribution/blob/acdfd89bce2a1fd965c048d66755ec5bfc366f81/checkstyle-tester/my_check.xml#L12-L13

yes, we should not fail to execute, but if grammar/JavaParser did not change failure should be the same and not show by diff tool.
