### ISSUE TITLE
automate diff.groovy execution for multiple configs

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/contribution#486]
Since it is necessary to separate Checkstyle modules from checkstyle_checks.xml into multiple configs (5+)  when generating check regression reports for grammar changes, I would like to have a script to automate this process.  

It would be nice to make a directory containing all checkstyle configs ( javadoc and sevntu checks, too ), point the script to the config directory, and have diff.groovy run once for each config.  The script should then place all the reports together in single output directory named after the branch thats being tested (in case multiple branches are run in succession), with each report named after the config file for easy identification and to make it easy for contributors to share with github.io, etc.  

This script would greatly simplify the report generation process, and make it easier to use diff.groovy in this case.

**Comment by rnveach** [comment]
Why don't you create a simple script that runs diff groovy for different files one after the other using the same arguments for the other parameters?

If you are looking for speed improvements like multi-threading, this would have to be something supported in Checkstyle or in diff groovy and not using the maven-checkstyle-plugin, otherwise you will need unique directory paths.

**Comment by nmancus1** [comment]
>Why don't you create a simple script that runs diff groovy for different files one after the other using the same arguments for the other parameters?

@rnveach this is exactly what I've written/ intended; if I've worded the issue poorly, let me know what I can clarify and I will rewrite it to make it more clear.

**Comment by rnveach** [comment]
No its clear, I just wanted sure if you wanted changes to diff.groovy or not.

While a script is a good temporary solution, not everyone runs on a specific OS, so any new additions would be better for diff.groovy (or a new groovy script) then a bash or bat script.

**Comment by nmancus1** [comment]
Honestly, I don't really see new additions to diff.groovy as an option. I think it is pretty complicated already. I hadn't considered writing a new groovy script, I guess that really does make the most sense from a platform-agnostic point of view.

**Comment by rnveach** [comment]
Unless @romani has some complaint, you can start a PR if you want.

**Comment by romani** [comment]
I have nothing against, we should keep in this repo all tools to simplify testing

**Comment by romani** [comment]
Fix is merged
