### ISSUE TITLE
diff report summary page misunderstood added diffs to removed diffs

### ISSUE THREAD

**Issue by Abhishek-kumar09** [checkstyle/contribution#493]
[diff report](https://abhishek-kumar09.github.io/checkstylereport/reports/diff/index.html)
https://github.com/checkstyle/contribution/blob/1928e99678e043fc2f7cc7b6cc41605df92a00bf/checkstyle-tester/diff.groovy#L391
Added diff regex: `totalPatch\">[0-9]++ .[0-9]++ removed, (?<totalAdd>[0-9]++)`
Removed diff regex: `totalPatch\">[0-9]++ .(?<totalRemoved>[0-9]++)`

In case when removed diff is 0, `removed` diff still matches its required regex which should be matched by `added` regex.

identified at: https://github.com/checkstyle/checkstyle/pull/8217#issuecomment-656093264

**Comment by rnveach** [comment]
Is this the same as https://github.com/checkstyle/checkstyle/pull/7932#issuecomment-675165946 ?

**Comment by Abhishek-kumar09** [comment]
@rnveach Yes, this is same just some problem with regex matching.

**Comment by Abhishek-kumar09** [comment]
I will be solving this problem, just busy with other commitments now a days.

**Comment by romani** [comment]
@Abhishek-kumar09 , thanks a lot for fix.
