### ISSUE TITLE
Add extraMvnOptions support to diff.groovy

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/contribution#523]
As we do for `launch.groovy`:
https://github.com/checkstyle/contribution/blob/fbccbcb591a0fd9cf4960659fbbc46f92e484300/checkstyle-tester/launch.groovy#L29

We should add this option to `diff.groovy`.  This will help us complete migration to `diff.groovy` from `launch.groovy`, especially in the case of https://github.com/checkstyle/checkstyle/issues/8901 where we depend on supplemental arguments to maven in regression testing.

**Comment by nmancus1** [comment]
@rnveach since we have removed JXR from Checkstyle-tester, is this still an issue?  The only usage of this option is in `no-exception-test.sh`:

```bash

➜  checkstyle git:(master) grep -R "extraMvnOptions"
.ci/no-exception-test.sh:      --extraMvnOptions "\"-Dmaven.jxr.skip=true\""
➜  checkstyle git:(master) 

```

In fact, we should probably just create an issue in Checkstyle now to remove this usage from `no-exception-test.sh`, right?   It runs to completion no problem now:

```bash
➜  checkstyle git:(master) ✗ ./.ci/no-exception-test.sh openjdk14-with-checks-nonjavadoc-error
CS_version: 8.40-SNAPSHOT
Cloning into 'contribution'...
...
Running Checkstyle on src/main/java ... with excludes {}
Running command: mvn -e --batch-mode site -Dcheckstyle.config.location=checks-nonjavadoc-error.xml -Dcheckstyle.excludes= -Dcheckstyle.version=8.40-SNAPSHOT
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dawt.useSystemAAFontSettings=gasp 
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...

...
[INFO] Generating "Checkstyle" report    --- maven-checkstyle-plugin:3.1.1
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18:05 min
[INFO] Finished at: 2021-01-13T11:27:48-05:00
[INFO] ------------------------------------------------------------------------
Running Checkstyle on src/main/java - finished
   [delete] Deleting directory /home/nick/IdeaProjects/checkstyle/.ci-temp/contribution/checkstyle-tester/src/main/java/openjdk14
     [move] Moving 37 files to /home/nick/IdeaProjects/checkstyle/.ci-temp/contribution/checkstyle-tester/reports/openjdk14
...
➜  checkstyle git:(master) ✗ grep -R "extraMvnOptions" 
➜  checkstyle git:(master) ✗ 

```

I can open a dummy PR in Checkstyle to show this if need be.

**Comment by rnveach** [comment]
I agree Checkstyle doesn't need the JXR skip anymore since there is no JXR and it can be removed.

`extraMvnOptions` may not have an immediate need right now, but if we don't transfer it to diff then it will be lost when we do #529 and have to be redone if a need arises. It could have some benefit in the future.

I leave it to you if you want to do this issue since you created it.

**Comment by rnveach** [comment]
@nmancus1 Please do the follow up in the main repo.

**Comment by rnveach** [comment]
@nmancus1 Is this issue done or are we missing something else?

**Comment by nmancus1** [comment]
We are good, I do not remember why I pushed additional changes after merge.

**Comment by rnveach** [comment]
Ok, then I am closing this if there is nothing more.
