### ISSUE TITLE
migrate all openjdk repositories in projects-to-test-on.properties to github mirrors

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/contribution#524]
From https://github.com/checkstyle/checkstyle/pull/8987:

> > I have noticed this failure several times before, should we consider switching to one of the mirrors on github?
> 
> yes, better to use git version of code (github).

_Originally posted by @romani in https://github.com/checkstyle/checkstyle/issues/8987#issuecomment-727583722_

We have experienced numerous failures with the openjdk mercurial repositories, we should change all to GitHub mirrors so that they will be more reliable in the future.

OpenJDK7: https://github.com/openjdk-mirror/jdk7u-jdk
OpenJDK8: https://github.com/AdoptOpenJDK/openjdk-jdk8u
OpenJDK9: https://github.com/AdoptOpenJDK/openjdk-jdk9u
OpenJDK10: https://github.com/AdoptOpenJDK/openjdk-jdk10u
OpenJDK11: https://github.com/AdoptOpenJDK/openjdk-jdk11u

**Comment by romani** [comment]
We can drop completely some old jdk that are easy to use

**Comment by nmancus1** [comment]
> We can drop completely some old jdk that are easy to use

7, 8?

**Comment by romani** [comment]
Yes, please, we can keep only latest.
As it will be less confusing for users to activate all or one.

Let's keep only one.

**Comment by rnveach** [comment]
@romani Why are we removing old JDKs from test on, but not others like circle?

https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-for-circle.properties#L8-L11

**Comment by romani** [comment]
it is accumulation of trash .... they need to be removed. No value now.
Lets keep jdk14 only with clear list of excludes - it is more valuable.

**Comment by nmancus1** [comment]
We can probably expand this issue to take care of all *.projects-*.properties., and if so, we can activate this after closing this issue: This project can be activated after this PR/ issue: https://github.com/checkstyle/checkstyle/blob/4c8ef953db33af72e1ee88645de826869f3fb186/.ci/shippable.sh#L59

**Comment by romani** [comment]
fix is merged
