### ISSUE TITLE
diff.groovy should allow configs to be placed in other directories

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/contribution#539]
As of https://github.com/checkstyle/contribution/commit/ed1f29895d9d0ea0eb20c6c7e1153961a89b5192, diff.groovy has not been able to generate crosslinked config files for the report summary outside of it's own directory. Noticed in numerous places, this limitation is causing failure for travis CI in https://github.com/checkstyle/regression-tool at https://travis-ci.org/github/checkstyle/regression-tool/jobs/755185633.  We have been using workarounds such as https://github.com/checkstyle/checkstyle/pull/9186/files#r560292164, but in the case of regression-tool, we would have to modify the tool to overcome this.

**Comment by romani** [comment]
Fix is merged
