### ISSUE TITLE
releasenotes-builder: fail execution if multiple labels (that define category) are applied

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#574]
Detected at https://github.com/checkstyle/checkstyle/issues/10842
Only one of "Bug", "Miscellaneous", "New Feature", "Breaking Compatibility" should be set of issue.

Better to fail build if uncertain situation happens.

**Comment by pbludov** [comment]
Only one of "Bug", "Miscellaneous", "New Feature", "Breaking Compatibility" should be set.

**Comment by Rahulkhinchi03** [comment]
@romani @rnveach I believe for this issue, what we are looking for is making a test case and checking if any of the four label is set and not more than one label from the above 4 label has been set to the issue?

**Comment by romani** [comment]
Yes, we miss logic to error execution when issue had two labels in same tim , for example "bug" and "miscellaneous".
