### ISSUE TITLE
Remove excludes warning from diff.groovy report

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/contribution#580]
When adding support for excludes to `diff.groovy` in #529 , we missed this:

https://github.com/checkstyle/contribution/blob/361bf4019fb062777d4922d79d2a52fefb53d342/checkstyle-tester/diff.groovy#L472

This line should be removed now that `diff.groovy` allows file exclusion.

**Comment by rnveach** [comment]
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L66

The line is still valid for difference regression. It is only NOT valid for old launch's no exception testing.

It requires a condition, and probably updated wording.

**Comment by nmancus1** [comment]
How about (if allowExcludes): `WARNING: Excludes are being ignored by diff.groovy. Excludes can be allowed by using the '--allowExcludes' option`?

Then also have (else) `WARNING: Excludes are being allowed by diff.groovy. This means that files and directories listed in the projects file are excluded from Checkstyle execution.` ?

**Comment by rnveach** [comment]
I am not really for telling users how to allow excludes in the report. Documentation should really speak for itself.

Truthfully, I think just the one warning is needed. I would rather it stand out that we aren't allowing excludes then have to read the 2 texts to find out which way was enabled for the reporting.

@romani ping

**Comment by nmancus1** [comment]
> I would rather it stand out that we aren't allowing excludes

On the contrary, I think that specifying that we **are** allowing excludes is more important. At least for me, I have been conditioned that diff reports never respect excluded files (as I am sure other frequent contributors are), and would find it valuable to know if files are being excluded from reports, and which ones. Having a warning that diff report generation is excluding files will cause me to take a harder look at the excluded file list in the generated projects file to see which files have been excluded, which I have glossed over in the past.

**Comment by nmancus1** [comment]
@rnveach updated PR, what do you think about:

Example of not allowing excludes: https://nmancus1.github.io/contrib/diff-not-allow/index.html

Example with allowing excludes: https://nmancus1.github.io/contrib/diff-allow/index.html

**Comment by romani** [comment]
Excludes make report more weak.
If user run all without excludes, it might be best form. But we used excludes to avoid exceptions, problems.

I would rather print in index page exclude list, to let reviewer see what part of project is excluded.

**Comment by nmancus1** [comment]
> I would rather print in index page exclude list, to let reviewer see what part of project is excluded.

This can be seen when viewing the projects file. Excludes list could be fairly large and projects file could have many projects, this would make the index page crowded.

**Comment by romani** [comment]
@nmancus1 ,

ok, we have option that control excludes. But it is:
> `g(longOpt: 'allowExcludes', required: false, 'Whether to allow excludes specified in the list`

not allow excludes by default.
So we need to update code that is referenced in issue description to print WARNING only if `allowExcludes` is `false` (not defined)

**Comment by rnveach** [comment]
Fix was merged
