### ISSUE TITLE
Update project commit id's in checkstyle-tester project files

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/contribution#590]
Noticed at https://github.com/checkstyle/checkstyle/pull/11100, many commit id's that use release versions (such as PMD, orekit, and others) need to be updated to use the newest release versions. This will require testing of each project. The easiest way to do this is to:

1. update each project to latest release commit, send PR to contribution
2. open a dummy PR in checkstyle main repo where most of these projects files are used, and replace cloned contribution repo to PR branch.
3. Make sure that all CI pass
4. In the case of `projects-to-test-on.properties`, we can use this projects file with github report generation action to show successful update

**Comment by rnveach** [comment]
Some commits are old because they had coding a specific way and then did an upgrade and like revamped their changes. Some are because they fail to keep project no-violation free.

**Comment by romani** [comment]
yes, we need to update this "release" commits from time to time.

**Comment by nmancus1** [comment]
Duplicate of https://github.com/checkstyle/contribution/issues/250
