### ISSUE TITLE
releasenotes-builder: Update releasenotes-builder to generate content to follow indentation in LI tag

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#612]
We need to updated code to do smart wrap of long lines into few lines with proper indentation.

if that is problem due to template engine we use, so I am ok with post generation processing of result xml.

```
    <section name="Release 10.4">
      <div class="releaseDate">30.07.2022</div>
      <p>Bug fixes:</p>
        <ul>
          <li>
            MissingJavadocType: Support qualified annotation names.
            Author: stoyanK7
            <a href="https://github.com/checkstyle/checkstyle/issues/11736">#11736</a>
          </li>
          <li>
            Update google_checks.xml to have the SuppressionCommentFilter and
SuppressWarningsHolder modules in the config by default (and by
extension, SuppressWarningsFilter).
            Author: Daniel del Castillo
            <a href="https://github.com/checkstyle/checkstyle/issues/11655">#11655</a>
          </li>
        </ul>
      <p>Notes:</p>

```

expected:
```
    <section name="Release 10.3.2">
      <div class="releaseDate">31.07.2022</div>
      <p>Bug fixes:</p>
        <ul>
          <li>
            MissingJavadocType: Support qualified annotation names.
            Author: stoyanK7
            <a href="https://github.com/checkstyle/checkstyle/issues/11736">#11736</a>
          </li>
          <li>
            Update google_checks.xml to have the SuppressionCommentFilter and
            SuppressWarningsHolder modules in the config by default (and by
            extension, SuppressWarningsFilter).
            Author: Daniel del Castillo
            <a href="https://github.com/checkstyle/checkstyle/issues/11655">#11655</a>
          </li>
        </ul>

```

**Comment by rnveach** [comment]
> generated content is violating limit of 100 symbols 

@romani Can you add examples? I thought we fixed most issues in https://github.com/checkstyle/contribution/issues/312 . Also not sure if this somehow applies to https://github.com/checkstyle/contribution/issues/364 or what.

**Comment by romani** [comment]
I updated description to describe actual problem

**Comment by Rahulkhinchi03** [comment]
@romani Do you want me to write some java code for this or we can do this after the post is created and the shell script focuses on the indentation? I believe shell script can do it more smartly.

Please share your thoughts!

**Comment by romani** [comment]
Shell script unlikely make it smart.
Please try to do this in java code of releasenotes builder.

**Comment by Rahulkhinchi03** [comment]
@romani @rnveach I tried some ways but are not satisfactory. Could you please guide me on how to resolve this issue?

**Comment by romani** [comment]
In a code where we already do wrap, you need to add indentation spaces to wrapped line, to make it looks indented

**Comment by Rahulkhinchi03** [comment]
If I am right, this is: https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java#L134-L191

**Comment by romani** [comment]
yes, this code was added for https://github.com/checkstyle/contribution/issues/312
see whole update to see updates in tests - https://github.com/checkstyle/contribution/commit/3a8c11285b15f7b40f441dcb2f495badcd5c81f3

**Comment by stoyanK7** [comment]
@romani Doesn't https://github.com/checkstyle/contribution/pull/677 that just got merged solve this issue as well?

**Comment by romani** [comment]
Yes
