### ISSUE TITLE
upgrade to latest IDEA inspection engine after issue in IDEA engine is fixed

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#622]
as https://youtrack.jetbrains.com/issue/IDEA-293720 fixed, try to upgrade to latest IDEA inspection engine
for now we downgraded to 2020.1.1 

https://teamcity-support.jetbrains.com/hc/en-us/requests/4153345

**Comment by MANISH-K-07** [comment]
@romani , This issue might be closed by my PR #837 ?

**Comment by romani** [comment]
Closed by https://github.com/checkstyle/contribution/pull/837#issuecomment-1981564485
