### ISSUE TITLE
releasenotes-builder: update Github template to be more compact

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#630]
now:
```
Checkstyle 10.4 - https://checkstyle.org/releasenotes.html#Release_10.4



Bug fixes:

  #11736 - MissingJavadocType: Support qualified annotation names
  #11655 - Update google_checks.xml to have the SuppressionCommentFilter ...

<details>
<summary>Other Changes:</summary>
<br>
  Update releasenotes to use ...
<br />
  Allow SuppressWarningHolder ....
```

expected ( attention to br tags):
```
Checkstyle 10.4 - https://checkstyle.org/releasenotes.html#Release_10.4

Bug fixes:

  #11736 - MissingJavadocType: Support qualified annotation names
  #11655 - Update google_checks.xml to have the SuppressionCommentFilter ....

<details>
<summary>Other Changes:</summary>
<br/>
  Update releasenotes to ... <br/>
  Allow SuppressWarningHolder ... <br/>

```

**Comment by romani** [comment]
https://cloud.drone.io/checkstyle/checkstyle/11997/4/2

Too much BR tags
```
<summary>Other Changes:</summary>
<br/>
  Kill surviving mutations in pitest-api <br/>
<br/>
  Solve fb-contrib errors <br/>
<br/>
```

Please make Junit test with few items

**Comment by Rahulkhinchi03** [comment]
Checkstyle 10.4-SNAPSHOT - https://checkstyle.org/releasenotes.html#Release_10.4-SNAPSHOT



Bug fixes:

  #11736 - MissingJavadocType: Support qualified annotation names
  #11655 - Update google_checks.xml to have the SuppressionCommentFilter and SuppressWarningsHolder modules in the config by default (and by extension, SuppressWarningsFilter)

<details>
<summary>Other Changes:</summary>
<br/>
  Adding CheckForVariable function to util.sh
<br/>
  Kill surviving mutations in pitest-api
<br/>
  Solve fb-contrib errors
<br/>
  update code base to have javadoc tag to explain noinspection tag content
<br/>
  Pitest: Kill all surviving mutations
<br/>
  doc: releasenotes for 10.3.2
<br/>
  Update releasenotes to use GitHub Pages execution
<br/>
  Allow SuppressWarningHolder to suppress the violation with NameCheck 
<br/>
  Pitest: Activate "ALL" mutator group 
<br/>
  Use Shellcheck to resolve violations code in Shell Script 
<br/>
  pitest: increase mutation coverage for pitest-imports profile to 100%  
<br/>
  Update GitHub Action for bump-license-year.sh 
<br/>
  Remove pitest mutation checking HTML model 
<br/>
  automate execution by Github action bump-license-year.sh on first day of month 
<br/>
  doc: put example of enableExternalDtdLoad to xdoc 
<br/>
  update doc for SuppressWarningsHolder 
<br/>
  releasenotes script generated empty commit 
<br/>
  Include CDG Accelerator Plugin to boost pitest performance 
<br/>
  Enforce file size on Java inputs 
<br/>
  Expand XPath IT Regression Testing 
<br/>
  There are semantic problems in the Chinese error message of keyword `design.forExtension` . 
<br/>
  prepare-settings.sh fails to create settings.xml 
<br/>
  Use groovy version provided by `apt` in pitest.yml 
<br/>
  tweet-releasenotes.sh does not check env variables 
<br/>
  download of m2 cache from sourceforge.io is slow 
<br/>
  infra: turns off create dependency reduced pom for shade plugin
<br/>
  Update Tests to use new 'verifyXxxxxx' method or 'execute' that use inlined config in Input files 
<br/>
  Specify violation messages in input files.
<br/>
  pitest: increase mutation coverage for javadoc profile to 100% 
</details>

**Comment by Rahulkhinchi03** [comment]
@romani We can remove the ending `BR tags` from each line. Please check: https://github.com/checkstyle/contribution/issues/630#issuecomment-1216509873

**Comment by romani** [comment]
Place br tags at end line as I requested at description

**Comment by Rahulkhinchi03** [comment]
Scope of this Issue:
-> I need to create a JUnit Test in [TemplateProcessorTest.java](https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java)
-> The JUnit should test if the `github_post.txt` an empty line.
