### ISSUE TITLE
releasenotes-builder: Release notes for GitHub shows escape at-symbol

### ISSUE THREAD

**Issue by Rahulkhinchi03** [checkstyle/contribution#652]
https://github.com/checkstyle/checkstyle/pull/12007#issuecomment-1221431907

**Comment by romani** [comment]
@stoyanK7 , can you help with this issue?

**Comment by stoyanK7** [comment]
@romani I am actually working on it. Submitting a pull request today.

**Comment by romani** [comment]
@stoyanK7 , please do not hesitate to send draft PR to let us see in what direction you are going.

**Comment by rnveach** [comment]
Fix was merged
