### ISSUE TITLE
Extend config of VariableDeclarationUsageDistance with validateBetweenScopes

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#661]
From https://github.com/checkstyle/checkstyle/pull/12052#issuecomment-1249593806

Update https://github.com/checkstyle/contribution/blob/21ad13659f978fc622f9d7c5f288b639a024ee30/checkstyle-tester/checks-nonjavadoc-error.xml#L349
To property that extends executed code of Check.

**Comment by nrmancuso** [comment]
Completed via #754
