### ISSUE TITLE
IDEA Docker Image documentation

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/contribution#669]
We need to replicate and improve README from https://github.com/nrmancuso/idea-inspections-docker. We should include details about how to execute inspections in container locally.

**Comment by MANISH-K-07** [comment]
@nrmancuso ,
I see that in our repo, we still don't have the README.md related to idea-inspections-docker from your vision.
Do you still want this to be done ?

If yes, I could send a PR with added readme file

**Comment by nrmancuso** [comment]
We can update/add it to https://github.com/checkstyle/contribution/blob/master/devops/docker/README.md

**Comment by MANISH-K-07** [comment]
Sorry for the confusion, your commit 9a840cd pretty much has everything that this doc might require :)
I couldn't find anything else that could improve your changes. Is this issue still necessary ?
