### ISSUE TITLE
invalid project commit in projects-to-test-on.properties

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#68]
https://github.com/checkstyle/contribution/blob/6c61d87084a031c9ca013d968705bf6bb5129e76/checkstyle-tester/projects-to-test-on.properties#L26

> apache-jsecurity|github|apache/jsecurity|89ffe41fddb62ad5f0349b17fb2a343d1f0dd152

Is converted to the URL: https://github.com/apache/jsecurity/tree/89ffe41fddb62ad5f0349b17fb2a343d1f0dd152

This points to a commit with no files in it. I noticed this during regression as AHSM complained about the missing XREF directory after a run on it.

**Comment by romani** [comment]
fixed, HEAD commit is used .
