### ISSUE TITLE
releasenotes builder: release version validation should work on digits

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#701]
now our version validation is based on amount of dots (very simple approach that use to work)

as we migrating to 3digits always release number number, see comment at https://github.com/checkstyle/checkstyle/discussions/12436
we need to improve logic and consider that 10.4 version will be 10.4.0.

it will help us naturally bump 10.4.0 to 10.4.1 without any intervention.  That is good for our new more frequent release model and validation of version.

**Comment by romani** [comment]
@stoyanK7 , please help to fix this.

**Comment by stoyanK7** [comment]
On it.

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
@romani @stoyanK7 
Can you explain why this error is correct with the version validation?
> [ERROR] Validation of release number failed. Release number is minor(10.0.0), but release notes do not contain 'new' or 'breaking compatability' labels. Please correct release number by running https://github.com/checkstyle/checkstyle/actions/workflows/bump-version-and-update-milestone.yml

Maybe it's just the sentence itself and not the logic, but I would not consider 10.0.0 a minor release number, especially if the previous release was 9.X.X . I assume it should say `Release number (10.0.0) is not minor, but....`

**Comment by stoyanK7** [comment]
For now, we differentiate between minor and patch, but do not check for major. If we follow SemVer, then yeah, `X.0.0` should be implemented and considered for major version, correct? And what labels should we check for then?

**Comment by romani** [comment]
For now we do not follow semiver.
First digit is emotional version.
We definitely can improve validation messaging later on. For now I would rather keep focus on make auto release to work.
