### ISSUE TITLE
deprecate RSS and mail list publishers

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#708]
Talked about at https://github.com/checkstyle/contribution/pull/705#issuecomment-1328068394 ,

we can probably deprecate RSS and mail list publishers, we do not use them.
The only I like of them is their format of output, it is easy to read and understand during review of release notes on decision to bump a version of change a label.
BUT now we have Github post , https://github.com/checkstyle/checkstyle/actions/runs/3554160972/jobs/5970086552#step:3:301
so it is good enough, we can completely remove Rss/Maillist templates and publishers

**Comment by nrmancuso** [comment]
Closed via https://github.com/checkstyle/contribution/pull/709#pullrequestreview-1195002910
