### ISSUE TITLE
releasenotes-builder: Exception on unknown Issue

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#711]
Identified at https://github.com/checkstyle/contribution/pull/705#discussion_r1032957057 ,

If an issue cannot be found, 
https://github.com/checkstyle/contribution/blob/21ad13659f978fc622f9d7c5f288b639a024ee30/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java#L147
releasenotes-builder will throw a `GHFileNotFoundException` and will kill the execution.

If this occurs it will be unable to process release notes. Since you cannot remove commits from Git at the time we get to this point, release note generation will be unable to continue and we would have to switch to manual creation. No output or such is created before this exception.

Even if we build safe guards into PRs and such to prevent this, Admins have direct push access and our commits are skipped by validation.

We should find an appropriate way to handle this in the utility if it ever occurs.

**Comment by rnveach** [comment]
Yes, as long as CI runs on Issue'd commits, it will be flagged. Just to be clear, maintainer will not be able to do anything with the releasenotes-builder as said above. It will stop processing in it's track.

**Comment by romani** [comment]
If CI is in bad state, do not release.
We always extra careful at such time.

In worse case we will have bad number of release it is not end of the world.

**Comment by rnveach** [comment]
@romani Should this issue be closed?

As a reminder, if this ever happens, release notes will not be able to be generated and we will either have to forgo release notes for a release or do them manually by hand and possibly be error prone.

**Comment by romani** [comment]
if it happens we will have red status on 
[![][release notes/version img]][release notes/version]

if this is not good sign for person who is going to make release, it will fail in the middle of release process and it will block it.
Unpleasant situation but it will teach to look at CI before release.

Do you suggest to make it as WARN and skip it ? 
to not actually block everything, and is maintainers does not care , it meant it it ok to not reference in release notes. 

[release notes/version]:https://github.com/checkstyle/checkstyle/actions/workflows/releasenotes-gen.yml
[release notes/version img]:https://github.com/checkstyle/checkstyle/actions/workflows/releasenotes-gen.yml/badge.svg

**Comment by rnveach** [comment]
I believe you have said that the release should still go even if CI is failing all over the place.

We should keep this as error so CI continues to fail on it in PRs. I think we should instead have a skip property for release notes that it skips all errors and continues on as best as it can to not fail. Like you said, for this issue it can use commit message. Everything that was an error before can be converted to a warn with the skip on. We will only use this property as a last resort for release process.

**Comment by romani** [comment]
we probably can not fail there, as if for some weird case wrong reference passed in master(for example CI are deactivated or failed to notify us on failure)  we can not fix it, we do not allow to change git history in master. So what is merged is set in stone.
We can not change commit and we can not change ids in Github.
 
All we can do is just put this update to "Notes" section of release notes. We do not need extra property.

**Comment by rnveach** [comment]
I was not saying to change git history. Property is just to turn error into warn so we can continue on if we have gotten to that case.

**Comment by romani** [comment]
releasenotes does not work in PR.
it works only on master, so no reason to have.

Please confirm that it is ok.

**Comment by rnveach** [comment]
I don't think it should be enabled all the time so its always a warn, but if thats what you want.

**Comment by romani** [comment]
I see no reason to do behavior customizable. It would not in use in our current usage. If something change in usage, we can always update code.

----

Resolution: we should do Warn and make default section "Notes" for all not found from GitHub.

**Comment by romani** [comment]
Fix is merged
