### ISSUE TITLE
Automate social posts (SF, RSS, twitter, g+, maillist)

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#73]
Assigned to @Vladlis .

Right now I do this manually, this should be automated.

Eventually it be launched on Travis automatically. Preferred languages, shell + java(if required) .

**Comment by Vladlis** [comment]
@romani 
1) the format for g+ and twitter is not obvious. I propose the following: https://plus.google.com/108692338295483568100/posts/K3pCdYH5wH1

2) I do not see any publications about releases in [maillist](https://groups.google.com/forum/#!forum/checkstyle) - will we start it? If so, then what format will we use - the same as in RSS and SF?

**Comment by romani** [comment]
> 1)

yes, that format is expected, just link and statistics on amount of updates.

> I do not see any publications about releases in mail-list - will we start it?

Special mail-list for announcements - https://groups.google.com/forum/#!forum/checkstyle-announce
Format the same as for Sourceforge.

**Comment by romani** [comment]
we need options:
- generateAll (all posts)
- generateXXXX (specific post)
- publishAll (publish all posts)
- publishXXXX (publish specific post)
- loginXXXX/pwdXXXX for each post to publish

such options are required to skip some publishing if it is become unstable or problematic.

**Comment by Vladlis** [comment]
@romani 
Please, review the last commit from this issue to confirm that I'm on the right way.

**Comment by romani** [comment]
sorry for long delay.

1)
> CliOptions

it is general it s good. There is only one bad side of this implementation of Builder is that `build()` method will return the same instance of CliOptoin of class, rather than new instance.
```
Builder builder = CliOptions.newBuilder() 
CliOption o = builder.releaseNotes(commandLine.getOptionValue(OPTION_R))
           .outputLocation(commandLine.getOptionValue(OPTION_O))
            ...
           .build();

CliOption o1 = builder.releaseNotes(commandLine.getOptionValue(OPTION_R))
           .outputLocation(commandLine.getOptionValue(OPTION_O))
            ...
           .build();

```

builder will return the same instance, but this is not obvious. Builder should always return new instance. User of this builder should trust a name and do not recheck how this builder is implemented.
I know that we have form of builder in checkstyle - it was my bad to allow it to appear.

**Comment by romani** [comment]
@Vladlis ,

so as we discussed before , Social posts is just another release notes generation,
the only nuances:
1) xdoc + social generation should be done before "mvn release:prepare"
2) publishing of xdoc (git commit & git push) should be done before "mvn release:prepare"
3) social publishing should be done after "release.sh" launch

So the difference is only time of publication.
Source of data is the same - git hostory + github lables.

We do not use auto-publication even for xdoc, it is still in testing.
So we could do the same for social, we could just generate content of posts that is ready to copy paste and integrate it to CI, it will help me use it in real releases.

As second step provide publications functionality base on generated files(post content).
it will help us gradually merge and use on local and at CIs.

Looks like we need to integrate social posts generation to releasenotes-xdoc-builder right now, amount of arguments will not be a problem.

we could use files as location of content between generation and publication.

**Comment by romani** [comment]
I do not see "DONE" on points that are posted before. Did you fixed them ?

7)
> generateSf

generateRss and generateSf is the same on SorceForce we post only in RSS feed. Please keep generateRss only.

**Comment by Vladlis** [comment]
After we moved implementation to releasenotes-xdoc-builder (I guess the project should be renamed in the end):

1) done

2) this option is not used now

3) 4) 5) 6) not relevant - https://github.com/checkstyle/contribution/pull/102

7) done - https://github.com/checkstyle/contribution/pull/101

8) I do not understand this part, please explain:
> will help to less attentive that naming is shortened as it is a builder

9) I ain't see a problem here - the javadoc is just rephrased and extended name, the meaning is the same. Am I misunderstanding smth? How the variable should be named?

10) But it is used here:
>         finally {
            if (errorCounter == 0) {
                System.out.println(String.format("%nGeneration succeed!"));
            }
            else {
                System.out.println(String.format("%nGeneration ends with %d errors.",
                    errorCounter));
                System.exit(EXIT_WITH_ERRORS_CODE);
            }
        }

`cliProcessor.hasErrors()` won't give the same result.

**Comment by MEZk** [comment]
@Vladlis 
8) I agree with @romani, as it is not clear from "generateXXX" method name whether it performs real generation or sets the option value. "setGenerateXXXX" is a good alternative if you can not find more appropriate name for the options.

**Comment by Vladlis** [comment]
@MEZk, 

8) I agree, that's a good point

9) the key word in the name of this variable is `CODE` which means, that it is a noun

**Comment by romani** [comment]
11) You are good to go with publish phase.
Please do publish direcly from files. For each publisher there should be separate class.

12) Please make update to README.md with new arguments.

13) As you also fun of IntelijIdea ... does it make sense to active IntelijIdea Inspections on this project ?
we can even setup validaton in Teamcity web service to prevent bad code from other contributors.
We can take configuration from Checkstyle but use different scope file.

14)
> EXIT_WITH_ERRORS_CODE

first of all, variable name can not start from verb - it is not an action, not a method.
As soon as you have only one code , please use just `ERROR_EXIT_CODE` .

> the javadoc is just rephrased and extended name

javadoc is more clear and not that verbose - red flag that initial name was taken badly.

> 8) I do not understand this part, please explain

Sorry, part of sentence was lost, I did it on the go.
So main idea is to make code clear to read with minimal amount of context awareness. If you read that chain methods (builder initialization) whole way up. You will understand that it is not actions is just a Builder, so naming is different from all other code. It takes time to understand it and it distracts.

**Comment by Vladlis** [comment]
@romani 
13) Done
14) Done
15) Done

I cannot proceed with publication to Gplus as it requires a Google for work account:

https://developers.google.com/+/domains/quickstart/java
> Open your Google Apps domain control panel, at https://www.google.com/a/cpanel/example.com

https://support.google.com/a/answer/182076?hl=en

**Comment by Vladlis** [comment]
There is also a problem with publication to RSS, as direct access to xml hosted on Sourceforge is required. It might be possible to use Sourceforge API somehow, but I did not find a way to do this.

**Comment by romani** [comment]
@Vladlis ,

> There is also a problem with publication to RSS, as direct access to xml hosted on Sourceforge is required

please provide a link , where you get to know this. Where this file is located ?

> I cannot proceed with publication to Gplus as it requires a Google for work account

I do not understand what is a problem, please find me in chat to discuss this.

**Comment by Vladlis** [comment]
@romani,
So far automatic publication is implemented only for xdoc and Twitter. As for the others:
1) Sourceforge provides RESTful API which allows publishung new posts to RSS, but it returns incorrect response code (checked with cURL) and therefore posting to RSS cannot be done without a "spike";
2) Google APIs do not give an ability

**Comment by romani** [comment]
@Vladlis , please add README.txt file to https://github.com/checkstyle/contribution/tree/master/releasenotes-builder/src/main/java/com/github/checkstyle/publishers
and place there examples of commands of how to run publishers from scratch.

instruction for xdoc publishing will be used by me at https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#before-starting

**Comment by Vladlis** [comment]
@romani,
Done

**Comment by romani** [comment]
@Vladlis , mail-list is still uncovered, should be possible to create topic by sending and email (through google's smtp server) - http://stackoverflow.com/questions/15597616/sending-email-via-gmail-smtp-server-in-java

**Comment by romani** [comment]
Mail list publication support is merged.

**Comment by romani** [comment]
> SF's support insisted that POST to https://sourceforge.net/rest/p/releasenotes-builder/new works good, but I could only get code 404 in response

@Vladlis ,  can you share details here. Link to issue againt SForge, ... . To make it clear what was tried and what we should wait from SForge to fix.

**Comment by romani** [comment]
final fix is merged.

So all publishers are done except for G+ (that demand payed account for api usage).
