### ISSUE TITLE
Update codenarc to latest version

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/contribution#757]
Noticed at https://github.com/checkstyle/contribution/pull/746/files#r1060109071, we are using an old version of codenarc. Latest release is 3.1.0, we are using 1.4/1.5 right now.

https://github.com/CodeNarc/CodeNarc/releases

Edit: we cannot use the latest due to older groovy version used in CI and the groovy syntax used in our scripts. We have settled on 2.2.0

**Comment by nrmancuso** [comment]
Closed via https://github.com/checkstyle/contribution/pull/836

**Comment by nrmancuso** [comment]
@MANISH-K-07 do we need to do the same in the main repo?

**Comment by MANISH-K-07** [comment]
> @MANISH-K-07 do we need to do the same in the main repo?

That was the idea, yes. I was waiting for this PR to get merged. Now, I will bump release in main repo

We are still using the older version `v1.4`
From checkstyle/[codenarc.groovy](https://github.com/checkstyle/checkstyle/blob/master/.ci/codenarc.groovy) : 

```
@Grapes(
        @Grab(group='org.codenarc', module='CodeNarc', version='1.4')
)
```

We might expect some violations as part of release bump....

**Comment by MANISH-K-07** [comment]
@nrmancuso ,

I have opened an issue in the main repo : https://github.com/checkstyle/checkstyle/issues/14556 (Issue)
Linked a PR that aims to close the above issue : https://github.com/checkstyle/checkstyle/pull/14558 (PR)

Please review....
