### ISSUE TITLE
Update checkstyle/jdk-11-groovy-git-mvn to use latest version of maven, git, and groovy

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/contribution#763]
We aim to run groovy scripts in a docker container to utilize the latest groovy version.
Main repo issue: https://github.com/checkstyle/checkstyle/issues/12646

File to be updated:

devops/docker/no-exception-build-image/jdk-11-groovy-git-mvn/Dockerfile

**Comment by Shubhamrajgithub** [comment]
Hi @Vyom-Yadav  is this issue still live ?

**Comment by Vyom-Yadav** [comment]
Yes

**Comment by Vyom-Yadav** [comment]
You need to update https://github.com/checkstyle/contribution/blob/master/devops/docker/maven-build-image/jdk-8u162b12/Dockerfile to use the latest version of maven, git, and groovy.

**Comment by Shubhamrajgithub** [comment]
@Vyom-Yadav  I have tried to update the packages in the above file, can you check that if it works.

**Comment by Vyom-Yadav** [comment]
@Shubhamrajgithub You need to create a pull request.

**Comment by romani** [comment]
Did we addressed this issue in your latest container?

**Comment by nrmancuso** [comment]
Since we are using Ubuntu, it was easier to use the version of groovy that is included, we needed to unblock maned version update in main repo. We can do a separate battle with custom groovy version in scope of this issue. We can do manual installation,  or try to layer docker images if that is easier and doesn’t bloat the image.

**Comment by Vyom-Yadav** [comment]
I don't understand why we don't use official groovy image as base and just install maven on those? Won't that sort our problem?

**Comment by romani** [comment]
We do not need latest groovy for sure :).

**Comment by Vyom-Yadav** [comment]
Let's close this issue then.
