### ISSUE TITLE
Create Travis and Appveyor test launches for patch-diff-report-tool 

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#79]
projects patch-diff-report-tool is tested by build process .

That is not enough, as we need to make sure that it is running well (similar to the way how we do this for checkstyle-tester).

Reason is to avoid problems like https://github.com/checkstyle/contribution/pull/77

**Comment by MEZk** [comment]
@romani 
Do we need to implement test launchers as diff.grovy already tests  patch-diff-report-tool with all arguments?

**Comment by romani** [comment]
This is old issue, before groovy.
It enough to has test launch only for groovy.

**Comment by rnveach** [comment]
@romani I think you accidentally re-opened this.

Aside, we might want to keep this open to start adding test and code coverage to the diff utility. I want to make some changes to it but I am afraid of breaking something without tests to verify.

**Comment by romani** [comment]
@rnveach , you are almost right.
to avoid any further misinterpretations I opened new issue #177.

**Comment by rnveach** [comment]
@romani Just to clarify, I believe this issue to be only for [patch-diff-report-tool](https://github.com/checkstyle/contribution/tree/master/patch-diff-report-tool) which is not groovy and not related to #177 .

**Comment by romani** [comment]
groovy will call this patch-diff-report-tool so will do some testing.
