### ISSUE TITLE
patch-diff-report-tool: some xref paths are too long for windows

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#82]
Example: M:\checkstyleWorkspace\gh_pages\3103\checkstyle\xref\home\ricky\opensource\contribution\checkstyle-tester\saverefs\checkstyle\checkstyle-checkstyle-f9ce38f\src\it\resources\com\google\checkstyle\test\chapter4formatting\rule42blockindentaion\InputIndentationCorrect.java.html
275 characters long.

The path is the fully qualified path of where the file existed when the tool was run.
For this tool, we only really care about the contents of the file and the contents of the main report. We can still display the fully qualified path on the main report, but is there any reason the java.html file has to have this long a path?

It would be nice if we shortened the path to just "\xref\some_name.java.html". Unless there is a reason we need the same file name as the original, it could be like "File1", "File2", etc.

**Comment by romani** [comment]
@rnveach , where exactlty windows has a problem ?

Common part of all files "M:\checkstyleWorkspace\gh_pages\3103\checkstyle\xref\home\ricky\opensource\contribution\checkstyle-tester" sould be removed in html.

**Comment by rnveach** [comment]
@romani
The problem is not with the HTML content but the physical folder structure.
When I tried to copy the output files that ran in my VM to Windows using WinSCP, some of the files in the deep folders failed to copy.

Windows has a notorious max path of around 255-260 characters.
https://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx#maxpath
> In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters.

**Comment by romani** [comment]
> When I tried to copy the output files that ran in my VM to Windows using WinSCP

please share details why you need this ?
if deep folder is created why there should be a problem to copy it. Some windows weirdness ....

**Comment by rnveach** [comment]
> if deep folder is created why there should be a problem to copy it

Deep folder was created in a VM on Ubuntu where it really has no restriction on max path length. The problem only arises when I try to copy those files out of the VM to Windows.

> please share details why you need this ?

I am a windows users, and windows is my main environment.
I really only use the VM for this utility because of the ease of batching multiple CS regressions with `launch.sh` and `launch_ahsm.sh`. I still use windows to update Git and all my other work.
Even if I didn't use the VM, this utility would still have the same problem running on Windows and will either fail when trying to create a file in such a deep path or fail trying to access it later making it harder to remove it (http://superuser.com/questions/718223/force-delete-files-with-a-rather-large-name).

**Comment by romani** [comment]
we do use checkstyle at windows build - https://ci.appveyor.com/project/Checkstyle/contribution/build/23/job/yyy4hktdc5tsievc
cmd: https://github.com/checkstyle/contribution/blob/master/appveyor.yml#L65

does this approach work for you ? can we reproduce this problem in appveyor ?

--------------

> It would be nice if we shortened the path to just "\xref\some_name.java.html". Unless there is a reason we need the same file name as the original,

When we test against real projects it is better to have real names/paths, Such reports we share with authors of projects to verify Check validation. I do not think any update would make it good.
But we could have special option for Windows users to post process report and shrink paths in report and in filesystem, but this dirty hack .... 

Can you move "M:\checkstyleWorkspace\gh_pages\3103\checkstyle\xref\home\ricky\opensource\contribution" to "M:\contrinution" ?

**Comment by rnveach** [comment]
> Can you move 

Yes, moving to a smaller path is always a fix as long as it shrinks it below 260.

> can we reproduce this problem in appveyor ?

I don't see why not. If you wish, I will try to do it.
It doesn't have to be even using this utility, as it is a general windows issue.

> When we test against real projects it is better to have real names/paths

If we need traceability, we can always add the original path to the top of the HTML Java File. Most people won't look at the physical file names and just what the report displays.

Example: Since you started reviewing it, if you missed it, my CS 3103's report used what I am proposing here as an example.
http://rnveach.github.io/checkstyle/3103/spring-framework/#A1
http://rnveach.github.io/checkstyle/3103/spring-framework/xref/File1.html#L83 (Note the `File1` and not `http://.../home/ricky/opensource/contribution/checkstyle-tester/saverefs/spring-framework/spring-projects-spring-framework-d166232/spring-aop/src/main/java/org/springframework/aop/aspectj/annotation/ReflectiveAspectJAdvisorFactory.java`)
http://rnveach.github.io/checkstyle/3103/spring-framework/#A3
http://rnveach.github.io/checkstyle/3103/spring-framework/xref/File2.html#L136
The only thing that changed was the XREF file name, not the report's printed file name.

> process report and shrink paths in report and in filesystem

This might be possible already with the option `refFiles`. It isn't really documented, but it says it uses that to shorten the paths.
https://github.com/checkstyle/contribution/blob/f64f59c907d40d8b0904a0e964b3d8e91ed72950/patch-diff-report-tool/src/main/java/com/github/checkstyle/site/XrefGenerator.java#L81

**Comment by romani** [comment]
Please try :) this option. I though it was only for shortening in report.

I am ok with tool update for windows only by special option as hack

**Comment by rnveach** [comment]
New CLI option is `--shortFilePaths`.

To modify the example at the bottom of https://github.com/rnveach/contribution/blob/92a0032c9a15d57b257e0c761fdd4de0280757ae/patch-diff-report-tool/README.md to use this new option, here is an example:
`java -jar ./patch-diff-report-tool-0.1-SNAPSHOT-jar-with-dependencies.jar --baseReport ~/contribution/checkstyle-tester/location1/checkstyle-result.xml --patchReport ~/contribution/checkstyle-tester/location2/checkstyle-result.xml --refFiles ~/contribution/checkstyle-tester/src/main/java --output ~/contribution/checkstyle-tester/site_result --baseConfig ~/contribution/checkstyle-tester/my_check.xml --patchConfig ~/contribution/checkstyle-tester/my_other_check.xml --shortFilePaths`

The change in the report this option does is very small and most people will miss it if they don't really look for it.
![example](https://cloud.githubusercontent.com/assets/5427943/22672494/5972c10a-eca2-11e6-80cb-0463241b4f7d.png)
Note that the displayed file name is the file project path, but the links to the HTML version of the file is shortened to just `FileXXX.html`.

**Comment by romani** [comment]
Fix is merged
