### ISSUE TITLE
patch-diff-report-tool: allow patchReport by itself

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#92]
`patch-diff-report-tool` only copies the needed files from the normal site command, trimming the amount of disk space the entire report needs. When running all projects, the before diff space used amounts to at least 1 gigabyte per branch for me.

However, for reports sometimes there is no base report, like when introducing a brand new Check.
It seems crazy to keep all those extra files and some utils are made to only read the `patch-diff-report-tool`'s html report (`launch_diff` creates a main html report for multiple diff reports).

It would be nice if `patch-diff-report-tool` allowed just the `patchReport` and assumed the `baseReport` is completely empty for its compares.

**Comment by romani** [comment]
> like when introducing a brand new Check.

I do not understand why for new Check checkstyle-tester is not enoungh

**Comment by rnveach** [comment]
`checkstyle-tester` is enough, but like I said, `patch-diff-report-tool` trims the amount of files down. After running `checkstyle-tester` by itself on all projects, the folders contain 1 gig of data (on 23 projects). I usually post all projects to the web and I don't think GH-IO will allow that much. The largest `patch-diff-report-tool` has been is around 40 megs so far.
Also my script `launch_diff` creates an easy to read index on all the projects, with quick access to violation counts. It currently only works for `patch-diff-report-tool`'s report format.

**Comment by romani** [comment]
> patch-diff-report-tool trims the amount of files down.

checkstyle-tester do(try) the same
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/launch.sh#L117
if not enough - lets fix it.

**Comment by rnveach** [comment]
I forgot about that.
That minimization won't work for me as we never solved the issue with: https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/launch.sh#L100
> Backuping files that are refenced in report ...
warning: <div not found.

It doesn't work correctly in my VM and thats why I just disabled it permamently.

**Comment by romani** [comment]
Ok. Please close this issue and open new issue with clear state of the problem
