### ISSUE TITLE
After merge for grammar update minimize exclude for java8/9 at /projects-for-circle.properties

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#93]
base on discussion at checkstyle/checkstyle#3230

@rnveach

>    not clear why we miss such failures by CI:

It is due to suppressions at checkstyle-tester/projects-for-circle.properties . Please provide an update to this file to minimize exclude scope as much as possible.

**Comment by rnveach** [comment]
2 more PRs and I will update the suppressions to the exact files.
